# File generated by stainful — DO NOT EDIT.
"""onebusaway — generated by stainful (the open-source Stainless)."""

from __future__ import annotations

from ._client import AsyncOnebusawaySDK, OnebusawaySDK
from ._core._exceptions import (
    APIConnectionError,
    APIError,
    APIResponseValidationError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    InternalServerError,
    InvalidWebhookSignatureError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    UnprocessableEntityError,
)
from ._core._sentinels import NOT_GIVEN, NotGiven, Omit, not_given, omit

OnebusawaySDKError = APIError

__all__ = ['OnebusawaySDK', 'AsyncOnebusawaySDK', 'OnebusawaySDKError', 'NotGiven', 'not_given', 'NOT_GIVEN', 'Omit', 'omit', 'APIConnectionError', 'APIError', 'APIResponseValidationError', 'APIStatusError', 'APITimeoutError', 'AuthenticationError', 'BadRequestError', 'ConflictError', 'InternalServerError', 'InvalidWebhookSignatureError', 'NotFoundError', 'PermissionDeniedError', 'RateLimitError', 'UnprocessableEntityError']
