# File generated by stainful — DO NOT EDIT.
"""onebusaway MCP server — generated by stainful.

Exposes the generated onebusaway SDK as a Model Context Protocol (MCP) server
over stdio. Run it under any MCP client (Claude Desktop, Cline, mcp-cli,
…):

    python -m onebusaway.mcp_server

Authentication is exactly the SDK's: the OnebusawaySDK client picks up its
configured env var on construction. 30 tools are exposed
(one per HTTP method).
"""

from __future__ import annotations

import asyncio
import json
from typing import Any

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

from . import OnebusawaySDK

_app: Server = Server('onebusaway')
_client_singleton: OnebusawaySDK | None = None


def _client() -> OnebusawaySDK:
    """Lazy-construct the SDK client on first tool call. Defers the
    `api_key` check (and env-var lookup) until the MCP server is
    actually invoked — so the module imports cleanly in tooling that
    only enumerates available servers."""
    global _client_singleton
    if _client_singleton is None:
        _client_singleton = OnebusawaySDK()
    return _client_singleton


def _to_text(result: Any) -> str:
    """Serialize an SDK return value (pydantic model / bytes / page / …)
    as a single text payload for MCP clients."""
    if isinstance(result, bytes):
        # Binary download — return base64 + a hint.
        import base64
        return json.dumps({
            "_kind": "binary",
            "base64": base64.b64encode(result).decode(),
        })
    if hasattr(result, "model_dump_json"):
        return result.model_dump_json()
    if hasattr(result, "__iter__") and not isinstance(result, (str, bytes)):
        # Paginated page — eagerly walk it (synchronously). Caller can
        # always set per_page/limit on the input if they want a slice.
        items: list = []
        for it in result:
            items.append(
                it.model_dump() if hasattr(it, "model_dump") else it
            )
        return json.dumps(items, default=str)
    return json.dumps(result, default=str)


@_app.list_tools()
async def list_tools() -> list[Tool]:
    return [
    Tool(
        name='agencies_with_coverage_list',
        description='Returns a list of all transit agencies currently supported by OneBusAway along with the center of their coverage area.',
        inputSchema={
                "properties": {},
                "type": "object"
        },
    ),
    Tool(
        name='agency_retrieve',
        description='Retrieve information for a specific transit agency identified by its unique ID.',
        inputSchema={
                "properties": {
                        "agency_id": {
                                "description": "The ID of the transit agency.",
                                "type": "string"
                        }
                },
                "required": [
                        "agency_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='vehicles_for_agency_list',
        description='Get vehicles for a specific agency',
        inputSchema={
                "properties": {
                        "agency_id": {
                                "description": "ID of the agency",
                                "type": "string"
                        },
                        "time": {
                                "type": "string"
                        }
                },
                "required": [
                        "agency_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='config_retrieve',
        description='config',
        inputSchema={
                "properties": {},
                "type": "object"
        },
    ),
    Tool(
        name='current_time_retrieve',
        description='current-time',
        inputSchema={
                "properties": {},
                "type": "object"
        },
    ),
    Tool(
        name='stops_for_location_list',
        description='stops-for-location',
        inputSchema={
                "properties": {
                        "lat": {
                                "type": "number"
                        },
                        "lat_span": {
                                "description": "An alternative to radius to set the search bounding box (optional)",
                                "type": "number"
                        },
                        "lon": {
                                "type": "number"
                        },
                        "lon_span": {
                                "description": "An alternative to radius to set the search bounding box (optional)",
                                "type": "number"
                        },
                        "query": {
                                "description": "A search query string to filter the results",
                                "type": "string"
                        },
                        "radius": {
                                "description": "The radius in meters to search within",
                                "type": "number"
                        }
                },
                "required": [
                        "lat",
                        "lon"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='stops_for_route_list',
        description='Get stops for a specific route',
        inputSchema={
                "properties": {
                        "include_polylines": {
                                "description": "Include polyline elements in the response (default true)",
                                "type": "boolean"
                        },
                        "route_id": {
                                "description": "ID of the route",
                                "type": "string"
                        },
                        "time": {
                                "description": "Specify service date (YYYY-MM-DD or epoch) (default today)",
                                "type": "string"
                        }
                },
                "required": [
                        "route_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='stops_for_agency_list',
        description='Get stops for a specific agency',
        inputSchema={
                "properties": {
                        "agency_id": {
                                "description": "ID of the agency",
                                "type": "string"
                        }
                },
                "required": [
                        "agency_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='stop_retrieve',
        description='Get details of a specific stop',
        inputSchema={
                "properties": {
                        "stop_id": {
                                "description": "ID of the stop",
                                "type": "string"
                        }
                },
                "required": [
                        "stop_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='stop_ids_for_agency_list',
        description='Get stop IDs for a specific agency',
        inputSchema={
                "properties": {
                        "agency_id": {
                                "description": "ID of the agency",
                                "type": "string"
                        }
                },
                "required": [
                        "agency_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='schedule_for_stop_retrieve',
        description='Get schedule for a specific stop',
        inputSchema={
                "properties": {
                        "date": {
                                "description": "The date for which you want to request a schedule in the format YYYY-MM-DD (optional, defaults to the current date)",
                                "format": "date",
                                "type": "string"
                        },
                        "stop_id": {
                                "description": "The stop id to request the schedule for, encoded directly in the URL",
                                "type": "string"
                        }
                },
                "required": [
                        "stop_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='route_retrieve',
        description='Retrieve information for a specific route identified by its unique ID.',
        inputSchema={
                "properties": {
                        "route_id": {
                                "description": "The ID of the route.",
                                "type": "string"
                        }
                },
                "required": [
                        "route_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='route_ids_for_agency_list',
        description='Get route IDs for a specific agency',
        inputSchema={
                "properties": {
                        "agency_id": {
                                "description": "ID of the agency",
                                "type": "string"
                        }
                },
                "required": [
                        "agency_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='routes_for_location_list',
        description='routes-for-location',
        inputSchema={
                "properties": {
                        "lat": {
                                "type": "number"
                        },
                        "lat_span": {
                                "type": "number"
                        },
                        "lon": {
                                "type": "number"
                        },
                        "lon_span": {
                                "type": "number"
                        },
                        "query": {
                                "type": "string"
                        },
                        "radius": {
                                "type": "number"
                        }
                },
                "required": [
                        "lat",
                        "lon"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='routes_for_agency_list',
        description='Retrieve the list of all routes for a particular agency by id',
        inputSchema={
                "properties": {
                        "agency_id": {
                                "description": "The id of the agency",
                                "type": "string"
                        }
                },
                "required": [
                        "agency_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='schedule_for_route_retrieve',
        description='Retrieve the full schedule for a route on a particular day',
        inputSchema={
                "properties": {
                        "date": {
                                "description": "The date for which you want to request a schedule in the format YYYY-MM-DD (optional, defaults to current date)",
                                "format": "date",
                                "type": "string"
                        },
                        "route_id": {
                                "description": "The route id to request the schedule for",
                                "type": "string"
                        }
                },
                "required": [
                        "route_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='arrivals_and_departures_for_location_list',
        description='Returns real-time arrival and departure data for stops within a bounding box or radius centered on a specific location.',
        inputSchema={
                "properties": {
                        "empty_returns_not_found": {
                                "description": "If true, returns a 404 Not Found error instead of an empty result.",
                                "type": "boolean"
                        },
                        "lat": {
                                "description": "The latitude coordinate of the search center.",
                                "type": "number"
                        },
                        "lat_span": {
                                "description": "Sets the latitude limits of the search bounding box.",
                                "type": "number"
                        },
                        "lon": {
                                "description": "The longitude coordinate of the search center.",
                                "type": "number"
                        },
                        "lon_span": {
                                "description": "Sets the longitude limits of the search bounding box.",
                                "type": "number"
                        },
                        "max_count": {
                                "description": "The max size of the list of nearby stops and arrivals to return. Defaults to 250, max 1000.",
                                "type": "integer"
                        },
                        "minutes_after": {
                                "description": "Include arrivals and departures this many minutes after the query time.",
                                "type": "integer"
                        },
                        "minutes_before": {
                                "description": "Include arrivals and departures this many minutes before the query time.",
                                "type": "integer"
                        },
                        "radius": {
                                "description": "The search radius in meters.",
                                "type": "number"
                        },
                        "route_type": {
                                "description": "Optional list of GTFS routeTypes to filter by (comma delimited) e.g. \"1,2,3\".",
                                "type": "string"
                        },
                        "time": {
                                "description": "By default, returns the status right now. Can be queried at a specific time (milliseconds since epoch) for testing.",
                                "type": "integer"
                        }
                },
                "required": [
                        "lat",
                        "lon"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='arrival_and_departure_list',
        description='arrivals-and-departures-for-stop',
        inputSchema={
                "properties": {
                        "minutes_after": {
                                "description": "Include vehicles arriving or departing in the next n minutes.",
                                "type": "integer"
                        },
                        "minutes_before": {
                                "description": "Include vehicles having arrived or departed in the previous n minutes.",
                                "type": "integer"
                        },
                        "stop_id": {
                                "type": "string"
                        },
                        "time": {
                                "description": "The specific time for querying the system status.",
                                "format": "date-time",
                                "type": "string"
                        }
                },
                "required": [
                        "stop_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='arrival_and_departure_retrieve',
        description='arrival-and-departure-for-stop',
        inputSchema={
                "properties": {
                        "service_date": {
                                "type": "integer"
                        },
                        "stop_id": {
                                "type": "string"
                        },
                        "stop_sequence": {
                                "type": "integer"
                        },
                        "time": {
                                "type": "integer"
                        },
                        "trip_id": {
                                "type": "string"
                        },
                        "vehicle_id": {
                                "type": "string"
                        }
                },
                "required": [
                        "service_date",
                        "stop_id",
                        "trip_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='trip_retrieve',
        description='Get details of a specific trip',
        inputSchema={
                "properties": {
                        "trip_id": {
                                "description": "ID of the trip",
                                "type": "string"
                        }
                },
                "required": [
                        "trip_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='trips_for_location_list',
        description='Retrieve trips for a given location',
        inputSchema={
                "properties": {
                        "include_schedule": {
                                "description": "Whether to include full schedule elements in the tripDetails section. Defaults to false.",
                                "type": "boolean"
                        },
                        "include_trip": {
                                "description": "Whether to include full trip elements in the references section. Defaults to false.",
                                "type": "boolean"
                        },
                        "lat": {
                                "description": "The latitude coordinate of the search center",
                                "type": "number"
                        },
                        "lat_span": {
                                "description": "Latitude span of the search bounding box",
                                "type": "number"
                        },
                        "lon": {
                                "description": "The longitude coordinate of the search center",
                                "type": "number"
                        },
                        "lon_span": {
                                "description": "Longitude span of the search bounding box",
                                "type": "number"
                        },
                        "time": {
                                "description": "Specific time for the query. Defaults to the current time.",
                                "type": "integer"
                        }
                },
                "required": [
                        "lat",
                        "lat_span",
                        "lon",
                        "lon_span"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='trip_details_retrieve',
        description='Retrieve Trip Details',
        inputSchema={
                "properties": {
                        "include_schedule": {
                                "description": "Whether to include the full schedule element in the tripDetails section (defaults to true).",
                                "type": "boolean"
                        },
                        "include_status": {
                                "description": "Whether to include the full status element in the tripDetails section (defaults to true).",
                                "type": "boolean"
                        },
                        "include_trip": {
                                "description": "Whether to include the full trip element in the references section (defaults to true).",
                                "type": "boolean"
                        },
                        "service_date": {
                                "description": "Service date for the trip as Unix time in milliseconds (optional).",
                                "type": "integer"
                        },
                        "time": {
                                "description": "Time parameter to query the system at a specific time (optional).",
                                "type": "integer"
                        },
                        "trip_id": {
                                "description": "ID of the trip to retrieve details for.",
                                "type": "string"
                        }
                },
                "required": [
                        "trip_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='trip_for_vehicle_retrieve',
        description='Retrieve trip for a specific vehicle',
        inputSchema={
                "properties": {
                        "include_schedule": {
                                "description": "Determines whether full <schedule/> element is included in the <tripDetails/> section. Defaults to false.",
                                "type": "boolean"
                        },
                        "include_status": {
                                "description": "Determines whether the full <status/> element is included in the <tripDetails/> section. Defaults to true.",
                                "type": "boolean"
                        },
                        "include_trip": {
                                "description": "Determines whether full <trip/> element is included in the <references/> section. Defaults to false.",
                                "type": "boolean"
                        },
                        "time": {
                                "description": "Time parameter to query the system at a specific time (optional).",
                                "type": "integer"
                        },
                        "vehicle_id": {
                                "description": "ID of the vehicle to retrieve trip details for.",
                                "type": "string"
                        }
                },
                "required": [
                        "vehicle_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='trips_for_route_list',
        description='Search for active trips for a specific route.',
        inputSchema={
                "properties": {
                        "include_schedule": {
                                "description": "Determine whether full schedule elements are included. Defaults to false.",
                                "type": "boolean"
                        },
                        "include_status": {
                                "description": "Determine whether full tripStatus elements with real-time information are included. Defaults to false.",
                                "type": "boolean"
                        },
                        "route_id": {
                                "description": "The ID of the route.",
                                "type": "string"
                        },
                        "time": {
                                "description": "Query the system at a specific time. Useful for testing.",
                                "type": "integer"
                        }
                },
                "required": [
                        "route_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='report_problem_with_stop_retrieve',
        description='Submit a user-generated problem report for a stop',
        inputSchema={
                "properties": {
                        "code": {
                                "description": "A string code identifying the nature of the problem",
                                "enum": [
                                        "stop_name_wrong",
                                        "stop_number_wrong",
                                        "stop_location_wrong",
                                        "route_or_trip_missing",
                                        "other"
                                ]
                        },
                        "stop_id": {
                                "description": "The ID of the stop",
                                "type": "string"
                        },
                        "user_comment": {
                                "description": "Additional comment text supplied by the user describing the problem",
                                "type": "string"
                        },
                        "user_lat": {
                                "description": "The reporting user\u2019s current latitude",
                                "type": "number"
                        },
                        "user_location_accuracy": {
                                "description": "The reporting user\u2019s location accuracy, in meters",
                                "type": "number"
                        },
                        "user_lon": {
                                "description": "The reporting user\u2019s current longitude",
                                "type": "number"
                        }
                },
                "required": [
                        "stop_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='report_problem_with_trip_retrieve',
        description='Submit a user-generated problem report for a particular trip.',
        inputSchema={
                "properties": {
                        "code": {
                                "description": "A string code identifying the nature of the problem",
                                "enum": [
                                        "vehicle_never_came",
                                        "vehicle_came_early",
                                        "vehicle_came_late",
                                        "wrong_headsign",
                                        "vehicle_does_not_stop_here",
                                        "other"
                                ]
                        },
                        "service_date": {
                                "description": "The service date of the trip",
                                "type": "integer"
                        },
                        "stop_id": {
                                "description": "A stop ID indicating where the user is experiencing the problem",
                                "type": "string"
                        },
                        "trip_id": {
                                "description": "The ID of the trip",
                                "type": "string"
                        },
                        "user_comment": {
                                "description": "Additional comment text supplied by the user describing the problem",
                                "type": "string"
                        },
                        "user_lat": {
                                "description": "The reporting user\u2019s current latitude",
                                "type": "number"
                        },
                        "user_location_accuracy": {
                                "description": "The reporting user\u2019s location accuracy, in meters",
                                "type": "number"
                        },
                        "user_lon": {
                                "description": "The reporting user\u2019s current longitude",
                                "type": "number"
                        },
                        "user_on_vehicle": {
                                "description": "Indicator if the user is on the transit vehicle experiencing the problem",
                                "type": "boolean"
                        },
                        "user_vehicle_number": {
                                "description": "The vehicle number, as reported by the user",
                                "type": "string"
                        },
                        "vehicle_id": {
                                "description": "The vehicle actively serving the trip",
                                "type": "string"
                        }
                },
                "required": [
                        "trip_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='search_for_stop_list',
        description='Search for a stop based on its name.',
        inputSchema={
                "properties": {
                        "input": {
                                "description": "The string to search for.",
                                "type": "string"
                        },
                        "max_count": {
                                "description": "The max number of results to return. Defaults to 20.",
                                "type": "integer"
                        }
                },
                "required": [
                        "input"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='search_for_route_list',
        description='Search for a route based on its name.',
        inputSchema={
                "properties": {
                        "input": {
                                "description": "The string to search for.",
                                "type": "string"
                        },
                        "max_count": {
                                "description": "The max number of results to return. Defaults to 20.",
                                "type": "integer"
                        }
                },
                "required": [
                        "input"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='block_retrieve',
        description='Get details of a specific block by ID',
        inputSchema={
                "properties": {
                        "block_id": {
                                "description": "ID of the block",
                                "type": "string"
                        }
                },
                "required": [
                        "block_id"
                ],
                "type": "object"
        },
    ),
    Tool(
        name='shape_retrieve',
        description='Retrieve a shape (the path traveled by a transit vehicle) by ID.',
        inputSchema={
                "properties": {
                        "shape_id": {
                                "description": "The shape ID, encoded directly in the URL",
                                "type": "string"
                        }
                },
                "required": [
                        "shape_id"
                ],
                "type": "object"
        },
    )
    ]


@_app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    arguments = dict(arguments or {})    # local copy; we may .pop() from it
    # `result` is intentionally untyped — each dispatch arm assigns a
    # different concrete response model, and we serialize via `_to_text`
    # before returning, so the loose typing is contained.
    result: Any
    if name == 'agencies_with_coverage_list':
        result = _client().agencies_with_coverage.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'agency_retrieve':
        agency_id = arguments.pop('agency_id')
        result = _client().agency.retrieve(agency_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'vehicles_for_agency_list':
        agency_id = arguments.pop('agency_id')
        result = _client().vehicles_for_agency.list(agency_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'config_retrieve':
        result = _client().config.retrieve(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'current_time_retrieve':
        result = _client().current_time.retrieve(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'stops_for_location_list':
        result = _client().stops_for_location.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'stops_for_route_list':
        route_id = arguments.pop('route_id')
        result = _client().stops_for_route.list(route_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'stops_for_agency_list':
        agency_id = arguments.pop('agency_id')
        result = _client().stops_for_agency.list(agency_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'stop_retrieve':
        stop_id = arguments.pop('stop_id')
        result = _client().stop.retrieve(stop_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'stop_ids_for_agency_list':
        agency_id = arguments.pop('agency_id')
        result = _client().stop_ids_for_agency.list(agency_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'schedule_for_stop_retrieve':
        stop_id = arguments.pop('stop_id')
        result = _client().schedule_for_stop.retrieve(stop_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'route_retrieve':
        route_id = arguments.pop('route_id')
        result = _client().route.retrieve(route_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'route_ids_for_agency_list':
        agency_id = arguments.pop('agency_id')
        result = _client().route_ids_for_agency.list(agency_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'routes_for_location_list':
        result = _client().routes_for_location.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'routes_for_agency_list':
        agency_id = arguments.pop('agency_id')
        result = _client().routes_for_agency.list(agency_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'schedule_for_route_retrieve':
        route_id = arguments.pop('route_id')
        result = _client().schedule_for_route.retrieve(route_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'arrivals_and_departures_for_location_list':
        result = _client().arrivals_and_departures_for_location.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'arrival_and_departure_list':
        stop_id = arguments.pop('stop_id')
        result = _client().arrival_and_departure.list(stop_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'arrival_and_departure_retrieve':
        stop_id = arguments.pop('stop_id')
        result = _client().arrival_and_departure.retrieve(stop_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'trip_retrieve':
        trip_id = arguments.pop('trip_id')
        result = _client().trip.retrieve(trip_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'trips_for_location_list':
        result = _client().trips_for_location.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'trip_details_retrieve':
        trip_id = arguments.pop('trip_id')
        result = _client().trip_details.retrieve(trip_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'trip_for_vehicle_retrieve':
        vehicle_id = arguments.pop('vehicle_id')
        result = _client().trip_for_vehicle.retrieve(vehicle_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'trips_for_route_list':
        route_id = arguments.pop('route_id')
        result = _client().trips_for_route.list(route_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'report_problem_with_stop_retrieve':
        stop_id = arguments.pop('stop_id')
        result = _client().report_problem_with_stop.retrieve(stop_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'report_problem_with_trip_retrieve':
        trip_id = arguments.pop('trip_id')
        result = _client().report_problem_with_trip.retrieve(trip_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'search_for_stop_list':
        result = _client().search_for_stop.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'search_for_route_list':
        result = _client().search_for_route.list(**arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'block_retrieve':
        block_id = arguments.pop('block_id')
        result = _client().block.retrieve(block_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    if name == 'shape_retrieve':
        shape_id = arguments.pop('shape_id')
        result = _client().shape.retrieve(shape_id, **arguments)
        return [TextContent(type='text', text=_to_text(result))]
    raise ValueError(f"Unknown tool: {name!r}")


async def main() -> None:
    async with stdio_server() as (read, write):
        await _app.run(read, write, _app.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
