# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import AgencyRetrieveResponse

__all__ = ["AgencyResource", "AsyncAgencyResource"]


class AgencyResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AgencyResourceWithRawResponse:
        return AgencyResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AgencyResourceWithStreamingResponse:
        return AgencyResourceWithStreamingResponse(self)

    def retrieve(
        self,
        agency_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AgencyRetrieveResponse:
        """Retrieve information for a specific transit agency identified by its unique ID."""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        return self._get(
            f"/api/where/agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=AgencyRetrieveResponse,
        )


class AsyncAgencyResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncAgencyResourceWithRawResponse:
        return AsyncAgencyResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncAgencyResourceWithStreamingResponse:
        return AsyncAgencyResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        agency_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AgencyRetrieveResponse:
        """Retrieve information for a specific transit agency identified by its unique ID."""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        return await self._get(
            f"/api/where/agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=AgencyRetrieveResponse,
        )


class AgencyResourceWithRawResponse:
    def __init__(self, agency: AgencyResource) -> None:
        self.retrieve = to_raw_response_wrapper(agency.retrieve)


class AsyncAgencyResourceWithRawResponse:
    def __init__(self, agency: AsyncAgencyResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(agency.retrieve)


class AgencyResourceWithStreamingResponse:
    def __init__(self, agency: AgencyResource) -> None:
        self.retrieve = to_streamed_response_wrapper(agency.retrieve)


class AsyncAgencyResourceWithStreamingResponse:
    def __init__(self, agency: AsyncAgencyResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(agency.retrieve)
