# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import AgenciesWithCoverageListResponse

__all__ = ["AgenciesWithCoverageResource", "AsyncAgenciesWithCoverageResource"]


class AgenciesWithCoverageResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AgenciesWithCoverageResourceWithRawResponse:
        return AgenciesWithCoverageResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AgenciesWithCoverageResourceWithStreamingResponse:
        return AgenciesWithCoverageResourceWithStreamingResponse(self)

    def list(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AgenciesWithCoverageListResponse:
        """Returns a list of all transit agencies currently supported by OneBusAway along with the center of their coverage area."""
        return self._get(
            f"/api/where/agencies-with-coverage.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=AgenciesWithCoverageListResponse,
        )


class AsyncAgenciesWithCoverageResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncAgenciesWithCoverageResourceWithRawResponse:
        return AsyncAgenciesWithCoverageResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncAgenciesWithCoverageResourceWithStreamingResponse:
        return AsyncAgenciesWithCoverageResourceWithStreamingResponse(self)

    async def list(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AgenciesWithCoverageListResponse:
        """Returns a list of all transit agencies currently supported by OneBusAway along with the center of their coverage area."""
        return await self._get(
            f"/api/where/agencies-with-coverage.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=AgenciesWithCoverageListResponse,
        )


class AgenciesWithCoverageResourceWithRawResponse:
    def __init__(self, agencies_with_coverage: AgenciesWithCoverageResource) -> None:
        self.list = to_raw_response_wrapper(agencies_with_coverage.list)


class AsyncAgenciesWithCoverageResourceWithRawResponse:
    def __init__(self, agencies_with_coverage: AsyncAgenciesWithCoverageResource) -> None:
        self.list = async_to_raw_response_wrapper(agencies_with_coverage.list)


class AgenciesWithCoverageResourceWithStreamingResponse:
    def __init__(self, agencies_with_coverage: AgenciesWithCoverageResource) -> None:
        self.list = to_streamed_response_wrapper(agencies_with_coverage.list)


class AsyncAgenciesWithCoverageResourceWithStreamingResponse:
    def __init__(self, agencies_with_coverage: AsyncAgenciesWithCoverageResource) -> None:
        self.list = async_to_streamed_response_wrapper(agencies_with_coverage.list)
