# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ArrivalAndDepartureListResponse, ArrivalAndDepartureRetrieveResponse

__all__ = ["ArrivalAndDepartureResource", "AsyncArrivalAndDepartureResource"]


class ArrivalAndDepartureResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ArrivalAndDepartureResourceWithRawResponse:
        return ArrivalAndDepartureResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ArrivalAndDepartureResourceWithStreamingResponse:
        return ArrivalAndDepartureResourceWithStreamingResponse(self)

    def list(
        self,
        stop_id: str,
        *,
        minutes_before: int | NotGiven = not_given,
        minutes_after: int | NotGiven = not_given,
        time: datetime | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ArrivalAndDepartureListResponse:
        """arrivals-and-departures-for-stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "minutesBefore": minutes_before,
            "minutesAfter": minutes_after,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/arrivals-and-departures-for-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ArrivalAndDepartureListResponse,
        )

    def retrieve(
        self,
        stop_id: str,
        *,
        trip_id: str | NotGiven = not_given,
        service_date: int | NotGiven = not_given,
        vehicle_id: str | NotGiven = not_given,
        stop_sequence: int | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ArrivalAndDepartureRetrieveResponse:
        """arrival-and-departure-for-stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "tripId": trip_id,
            "serviceDate": service_date,
            "vehicleId": vehicle_id,
            "stopSequence": stop_sequence,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/arrival-and-departure-for-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ArrivalAndDepartureRetrieveResponse,
        )


class AsyncArrivalAndDepartureResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncArrivalAndDepartureResourceWithRawResponse:
        return AsyncArrivalAndDepartureResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncArrivalAndDepartureResourceWithStreamingResponse:
        return AsyncArrivalAndDepartureResourceWithStreamingResponse(self)

    async def list(
        self,
        stop_id: str,
        *,
        minutes_before: int | NotGiven = not_given,
        minutes_after: int | NotGiven = not_given,
        time: datetime | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ArrivalAndDepartureListResponse:
        """arrivals-and-departures-for-stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "minutesBefore": minutes_before,
            "minutesAfter": minutes_after,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/arrivals-and-departures-for-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ArrivalAndDepartureListResponse,
        )

    async def retrieve(
        self,
        stop_id: str,
        *,
        trip_id: str | NotGiven = not_given,
        service_date: int | NotGiven = not_given,
        vehicle_id: str | NotGiven = not_given,
        stop_sequence: int | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ArrivalAndDepartureRetrieveResponse:
        """arrival-and-departure-for-stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "tripId": trip_id,
            "serviceDate": service_date,
            "vehicleId": vehicle_id,
            "stopSequence": stop_sequence,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/arrival-and-departure-for-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ArrivalAndDepartureRetrieveResponse,
        )


class ArrivalAndDepartureResourceWithRawResponse:
    def __init__(self, arrival_and_departure: ArrivalAndDepartureResource) -> None:
        self.list = to_raw_response_wrapper(arrival_and_departure.list)
        self.retrieve = to_raw_response_wrapper(arrival_and_departure.retrieve)


class AsyncArrivalAndDepartureResourceWithRawResponse:
    def __init__(self, arrival_and_departure: AsyncArrivalAndDepartureResource) -> None:
        self.list = async_to_raw_response_wrapper(arrival_and_departure.list)
        self.retrieve = async_to_raw_response_wrapper(arrival_and_departure.retrieve)


class ArrivalAndDepartureResourceWithStreamingResponse:
    def __init__(self, arrival_and_departure: ArrivalAndDepartureResource) -> None:
        self.list = to_streamed_response_wrapper(arrival_and_departure.list)
        self.retrieve = to_streamed_response_wrapper(arrival_and_departure.retrieve)


class AsyncArrivalAndDepartureResourceWithStreamingResponse:
    def __init__(self, arrival_and_departure: AsyncArrivalAndDepartureResource) -> None:
        self.list = async_to_streamed_response_wrapper(arrival_and_departure.list)
        self.retrieve = async_to_streamed_response_wrapper(arrival_and_departure.retrieve)
