# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ArrivalsAndDeparturesForLocationListResponse

__all__ = ["ArrivalsAndDeparturesForLocationResource", "AsyncArrivalsAndDeparturesForLocationResource"]


class ArrivalsAndDeparturesForLocationResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ArrivalsAndDeparturesForLocationResourceWithRawResponse:
        return ArrivalsAndDeparturesForLocationResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ArrivalsAndDeparturesForLocationResourceWithStreamingResponse:
        return ArrivalsAndDeparturesForLocationResourceWithStreamingResponse(self)

    def list(
        self,
        *,
        lat: float | NotGiven = not_given,
        lon: float | NotGiven = not_given,
        radius: float | NotGiven = not_given,
        lat_span: float | NotGiven = not_given,
        lon_span: float | NotGiven = not_given,
        time: int | NotGiven = not_given,
        minutes_before: int | NotGiven = not_given,
        minutes_after: int | NotGiven = not_given,
        max_count: int | NotGiven = not_given,
        route_type: str | NotGiven = not_given,
        empty_returns_not_found: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ArrivalsAndDeparturesForLocationListResponse:
        """arrivals-and-departures-for-location"""
        _params = {
            "lat": lat,
            "lon": lon,
            "radius": radius,
            "latSpan": lat_span,
            "lonSpan": lon_span,
            "time": time,
            "minutesBefore": minutes_before,
            "minutesAfter": minutes_after,
            "maxCount": max_count,
            "routeType": route_type,
            "emptyReturnsNotFound": empty_returns_not_found,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/arrivals-and-departures-for-location.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ArrivalsAndDeparturesForLocationListResponse,
        )


class AsyncArrivalsAndDeparturesForLocationResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncArrivalsAndDeparturesForLocationResourceWithRawResponse:
        return AsyncArrivalsAndDeparturesForLocationResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncArrivalsAndDeparturesForLocationResourceWithStreamingResponse:
        return AsyncArrivalsAndDeparturesForLocationResourceWithStreamingResponse(self)

    async def list(
        self,
        *,
        lat: float | NotGiven = not_given,
        lon: float | NotGiven = not_given,
        radius: float | NotGiven = not_given,
        lat_span: float | NotGiven = not_given,
        lon_span: float | NotGiven = not_given,
        time: int | NotGiven = not_given,
        minutes_before: int | NotGiven = not_given,
        minutes_after: int | NotGiven = not_given,
        max_count: int | NotGiven = not_given,
        route_type: str | NotGiven = not_given,
        empty_returns_not_found: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ArrivalsAndDeparturesForLocationListResponse:
        """arrivals-and-departures-for-location"""
        _params = {
            "lat": lat,
            "lon": lon,
            "radius": radius,
            "latSpan": lat_span,
            "lonSpan": lon_span,
            "time": time,
            "minutesBefore": minutes_before,
            "minutesAfter": minutes_after,
            "maxCount": max_count,
            "routeType": route_type,
            "emptyReturnsNotFound": empty_returns_not_found,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/arrivals-and-departures-for-location.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ArrivalsAndDeparturesForLocationListResponse,
        )


class ArrivalsAndDeparturesForLocationResourceWithRawResponse:
    def __init__(self, arrivals_and_departures_for_location: ArrivalsAndDeparturesForLocationResource) -> None:
        self.list = to_raw_response_wrapper(arrivals_and_departures_for_location.list)


class AsyncArrivalsAndDeparturesForLocationResourceWithRawResponse:
    def __init__(self, arrivals_and_departures_for_location: AsyncArrivalsAndDeparturesForLocationResource) -> None:
        self.list = async_to_raw_response_wrapper(arrivals_and_departures_for_location.list)


class ArrivalsAndDeparturesForLocationResourceWithStreamingResponse:
    def __init__(self, arrivals_and_departures_for_location: ArrivalsAndDeparturesForLocationResource) -> None:
        self.list = to_streamed_response_wrapper(arrivals_and_departures_for_location.list)


class AsyncArrivalsAndDeparturesForLocationResourceWithStreamingResponse:
    def __init__(self, arrivals_and_departures_for_location: AsyncArrivalsAndDeparturesForLocationResource) -> None:
        self.list = async_to_streamed_response_wrapper(arrivals_and_departures_for_location.list)
