# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import BlockRetrieveResponse

__all__ = ["BlockResource", "AsyncBlockResource"]


class BlockResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> BlockResourceWithRawResponse:
        return BlockResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> BlockResourceWithStreamingResponse:
        return BlockResourceWithStreamingResponse(self)

    def retrieve(
        self,
        block_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BlockRetrieveResponse:
        """Get details of a specific block by ID"""
        if not block_id:
            raise ValueError(
                f"Expected a non-empty value for `block_id` but received {block_id!r}"
            )
        return self._get(
            f"/api/where/block/{block_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=BlockRetrieveResponse,
        )


class AsyncBlockResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncBlockResourceWithRawResponse:
        return AsyncBlockResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncBlockResourceWithStreamingResponse:
        return AsyncBlockResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        block_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BlockRetrieveResponse:
        """Get details of a specific block by ID"""
        if not block_id:
            raise ValueError(
                f"Expected a non-empty value for `block_id` but received {block_id!r}"
            )
        return await self._get(
            f"/api/where/block/{block_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=BlockRetrieveResponse,
        )


class BlockResourceWithRawResponse:
    def __init__(self, block: BlockResource) -> None:
        self.retrieve = to_raw_response_wrapper(block.retrieve)


class AsyncBlockResourceWithRawResponse:
    def __init__(self, block: AsyncBlockResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(block.retrieve)


class BlockResourceWithStreamingResponse:
    def __init__(self, block: BlockResource) -> None:
        self.retrieve = to_streamed_response_wrapper(block.retrieve)


class AsyncBlockResourceWithStreamingResponse:
    def __init__(self, block: AsyncBlockResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(block.retrieve)
