# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import CurrentTimeRetrieveResponse

__all__ = ["CurrentTimeResource", "AsyncCurrentTimeResource"]


class CurrentTimeResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> CurrentTimeResourceWithRawResponse:
        return CurrentTimeResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> CurrentTimeResourceWithStreamingResponse:
        return CurrentTimeResourceWithStreamingResponse(self)

    def retrieve(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> CurrentTimeRetrieveResponse:
        """current-time"""
        return self._get(
            f"/api/where/current-time.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=CurrentTimeRetrieveResponse,
        )


class AsyncCurrentTimeResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncCurrentTimeResourceWithRawResponse:
        return AsyncCurrentTimeResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncCurrentTimeResourceWithStreamingResponse:
        return AsyncCurrentTimeResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> CurrentTimeRetrieveResponse:
        """current-time"""
        return await self._get(
            f"/api/where/current-time.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=CurrentTimeRetrieveResponse,
        )


class CurrentTimeResourceWithRawResponse:
    def __init__(self, current_time: CurrentTimeResource) -> None:
        self.retrieve = to_raw_response_wrapper(current_time.retrieve)


class AsyncCurrentTimeResourceWithRawResponse:
    def __init__(self, current_time: AsyncCurrentTimeResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(current_time.retrieve)


class CurrentTimeResourceWithStreamingResponse:
    def __init__(self, current_time: CurrentTimeResource) -> None:
        self.retrieve = to_streamed_response_wrapper(current_time.retrieve)


class AsyncCurrentTimeResourceWithStreamingResponse:
    def __init__(self, current_time: AsyncCurrentTimeResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(current_time.retrieve)
