# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from typing import Literal

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ResponseWrapper

__all__ = ["ReportProblemWithTripResource", "AsyncReportProblemWithTripResource"]


class ReportProblemWithTripResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ReportProblemWithTripResourceWithRawResponse:
        return ReportProblemWithTripResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ReportProblemWithTripResourceWithStreamingResponse:
        return ReportProblemWithTripResourceWithStreamingResponse(self)

    def retrieve(
        self,
        trip_id: str,
        *,
        service_date: int | NotGiven = not_given,
        vehicle_id: str | NotGiven = not_given,
        stop_id: str | NotGiven = not_given,
        code: Literal['vehicle_never_came', 'vehicle_came_early', 'vehicle_came_late', 'wrong_headsign', 'vehicle_does_not_stop_here', 'other'] | NotGiven = not_given,
        user_comment: str | NotGiven = not_given,
        user_on_vehicle: bool | NotGiven = not_given,
        user_vehicle_number: str | NotGiven = not_given,
        user_lat: float | NotGiven = not_given,
        user_lon: float | NotGiven = not_given,
        user_location_accuracy: float | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ResponseWrapper:
        """Submit a user-generated problem report for a particular trip."""
        if not trip_id:
            raise ValueError(
                f"Expected a non-empty value for `trip_id` but received {trip_id!r}"
            )
        _params = {
            "serviceDate": service_date,
            "vehicleID": vehicle_id,
            "stopID": stop_id,
            "code": code,
            "userComment": user_comment,
            "userOnVehicle": user_on_vehicle,
            "userVehicleNumber": user_vehicle_number,
            "userLat": user_lat,
            "userLon": user_lon,
            "userLocationAccuracy": user_location_accuracy,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/report-problem-with-trip/{trip_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ResponseWrapper,
        )


class AsyncReportProblemWithTripResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncReportProblemWithTripResourceWithRawResponse:
        return AsyncReportProblemWithTripResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncReportProblemWithTripResourceWithStreamingResponse:
        return AsyncReportProblemWithTripResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        trip_id: str,
        *,
        service_date: int | NotGiven = not_given,
        vehicle_id: str | NotGiven = not_given,
        stop_id: str | NotGiven = not_given,
        code: Literal['vehicle_never_came', 'vehicle_came_early', 'vehicle_came_late', 'wrong_headsign', 'vehicle_does_not_stop_here', 'other'] | NotGiven = not_given,
        user_comment: str | NotGiven = not_given,
        user_on_vehicle: bool | NotGiven = not_given,
        user_vehicle_number: str | NotGiven = not_given,
        user_lat: float | NotGiven = not_given,
        user_lon: float | NotGiven = not_given,
        user_location_accuracy: float | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ResponseWrapper:
        """Submit a user-generated problem report for a particular trip."""
        if not trip_id:
            raise ValueError(
                f"Expected a non-empty value for `trip_id` but received {trip_id!r}"
            )
        _params = {
            "serviceDate": service_date,
            "vehicleID": vehicle_id,
            "stopID": stop_id,
            "code": code,
            "userComment": user_comment,
            "userOnVehicle": user_on_vehicle,
            "userVehicleNumber": user_vehicle_number,
            "userLat": user_lat,
            "userLon": user_lon,
            "userLocationAccuracy": user_location_accuracy,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/report-problem-with-trip/{trip_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ResponseWrapper,
        )


class ReportProblemWithTripResourceWithRawResponse:
    def __init__(self, report_problem_with_trip: ReportProblemWithTripResource) -> None:
        self.retrieve = to_raw_response_wrapper(report_problem_with_trip.retrieve)


class AsyncReportProblemWithTripResourceWithRawResponse:
    def __init__(self, report_problem_with_trip: AsyncReportProblemWithTripResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(report_problem_with_trip.retrieve)


class ReportProblemWithTripResourceWithStreamingResponse:
    def __init__(self, report_problem_with_trip: ReportProblemWithTripResource) -> None:
        self.retrieve = to_streamed_response_wrapper(report_problem_with_trip.retrieve)


class AsyncReportProblemWithTripResourceWithStreamingResponse:
    def __init__(self, report_problem_with_trip: AsyncReportProblemWithTripResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(report_problem_with_trip.retrieve)
