# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from typing import Literal

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ResponseWrapper

__all__ = ["ReportProblemWithStopResource", "AsyncReportProblemWithStopResource"]


class ReportProblemWithStopResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ReportProblemWithStopResourceWithRawResponse:
        return ReportProblemWithStopResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ReportProblemWithStopResourceWithStreamingResponse:
        return ReportProblemWithStopResourceWithStreamingResponse(self)

    def retrieve(
        self,
        stop_id: str,
        *,
        code: Literal['stop_name_wrong', 'stop_number_wrong', 'stop_location_wrong', 'route_or_trip_missing', 'other'] | NotGiven = not_given,
        user_comment: str | NotGiven = not_given,
        user_lat: float | NotGiven = not_given,
        user_lon: float | NotGiven = not_given,
        user_location_accuracy: float | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ResponseWrapper:
        """Submit a user-generated problem report for a stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "code": code,
            "userComment": user_comment,
            "userLat": user_lat,
            "userLon": user_lon,
            "userLocationAccuracy": user_location_accuracy,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/report-problem-with-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ResponseWrapper,
        )


class AsyncReportProblemWithStopResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncReportProblemWithStopResourceWithRawResponse:
        return AsyncReportProblemWithStopResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncReportProblemWithStopResourceWithStreamingResponse:
        return AsyncReportProblemWithStopResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        stop_id: str,
        *,
        code: Literal['stop_name_wrong', 'stop_number_wrong', 'stop_location_wrong', 'route_or_trip_missing', 'other'] | NotGiven = not_given,
        user_comment: str | NotGiven = not_given,
        user_lat: float | NotGiven = not_given,
        user_lon: float | NotGiven = not_given,
        user_location_accuracy: float | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ResponseWrapper:
        """Submit a user-generated problem report for a stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "code": code,
            "userComment": user_comment,
            "userLat": user_lat,
            "userLon": user_lon,
            "userLocationAccuracy": user_location_accuracy,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/report-problem-with-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ResponseWrapper,
        )


class ReportProblemWithStopResourceWithRawResponse:
    def __init__(self, report_problem_with_stop: ReportProblemWithStopResource) -> None:
        self.retrieve = to_raw_response_wrapper(report_problem_with_stop.retrieve)


class AsyncReportProblemWithStopResourceWithRawResponse:
    def __init__(self, report_problem_with_stop: AsyncReportProblemWithStopResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(report_problem_with_stop.retrieve)


class ReportProblemWithStopResourceWithStreamingResponse:
    def __init__(self, report_problem_with_stop: ReportProblemWithStopResource) -> None:
        self.retrieve = to_streamed_response_wrapper(report_problem_with_stop.retrieve)


class AsyncReportProblemWithStopResourceWithStreamingResponse:
    def __init__(self, report_problem_with_stop: AsyncReportProblemWithStopResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(report_problem_with_stop.retrieve)
