# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import RouteRetrieveResponse

__all__ = ["RouteResource", "AsyncRouteResource"]


class RouteResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> RouteResourceWithRawResponse:
        return RouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> RouteResourceWithStreamingResponse:
        return RouteResourceWithStreamingResponse(self)

    def retrieve(
        self,
        route_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RouteRetrieveResponse:
        """Retrieve information for a specific route identified by its unique ID."""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        return self._get(
            f"/api/where/route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=RouteRetrieveResponse,
        )


class AsyncRouteResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncRouteResourceWithRawResponse:
        return AsyncRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncRouteResourceWithStreamingResponse:
        return AsyncRouteResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        route_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RouteRetrieveResponse:
        """Retrieve information for a specific route identified by its unique ID."""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        return await self._get(
            f"/api/where/route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=RouteRetrieveResponse,
        )


class RouteResourceWithRawResponse:
    def __init__(self, route: RouteResource) -> None:
        self.retrieve = to_raw_response_wrapper(route.retrieve)


class AsyncRouteResourceWithRawResponse:
    def __init__(self, route: AsyncRouteResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(route.retrieve)


class RouteResourceWithStreamingResponse:
    def __init__(self, route: RouteResource) -> None:
        self.retrieve = to_streamed_response_wrapper(route.retrieve)


class AsyncRouteResourceWithStreamingResponse:
    def __init__(self, route: AsyncRouteResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(route.retrieve)
