# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import RoutesForLocationListResponse

__all__ = ["RoutesForLocationResource", "AsyncRoutesForLocationResource"]


class RoutesForLocationResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> RoutesForLocationResourceWithRawResponse:
        return RoutesForLocationResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> RoutesForLocationResourceWithStreamingResponse:
        return RoutesForLocationResourceWithStreamingResponse(self)

    def list(
        self,
        *,
        lat: float | NotGiven = not_given,
        lon: float | NotGiven = not_given,
        radius: float | NotGiven = not_given,
        lat_span: float | NotGiven = not_given,
        lon_span: float | NotGiven = not_given,
        query: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RoutesForLocationListResponse:
        """routes-for-location"""
        _params = {
            "lat": lat,
            "lon": lon,
            "radius": radius,
            "latSpan": lat_span,
            "lonSpan": lon_span,
            "query": query,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/routes-for-location.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=RoutesForLocationListResponse,
        )


class AsyncRoutesForLocationResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncRoutesForLocationResourceWithRawResponse:
        return AsyncRoutesForLocationResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncRoutesForLocationResourceWithStreamingResponse:
        return AsyncRoutesForLocationResourceWithStreamingResponse(self)

    async def list(
        self,
        *,
        lat: float | NotGiven = not_given,
        lon: float | NotGiven = not_given,
        radius: float | NotGiven = not_given,
        lat_span: float | NotGiven = not_given,
        lon_span: float | NotGiven = not_given,
        query: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RoutesForLocationListResponse:
        """routes-for-location"""
        _params = {
            "lat": lat,
            "lon": lon,
            "radius": radius,
            "latSpan": lat_span,
            "lonSpan": lon_span,
            "query": query,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/routes-for-location.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=RoutesForLocationListResponse,
        )


class RoutesForLocationResourceWithRawResponse:
    def __init__(self, routes_for_location: RoutesForLocationResource) -> None:
        self.list = to_raw_response_wrapper(routes_for_location.list)


class AsyncRoutesForLocationResourceWithRawResponse:
    def __init__(self, routes_for_location: AsyncRoutesForLocationResource) -> None:
        self.list = async_to_raw_response_wrapper(routes_for_location.list)


class RoutesForLocationResourceWithStreamingResponse:
    def __init__(self, routes_for_location: RoutesForLocationResource) -> None:
        self.list = to_streamed_response_wrapper(routes_for_location.list)


class AsyncRoutesForLocationResourceWithStreamingResponse:
    def __init__(self, routes_for_location: AsyncRoutesForLocationResource) -> None:
        self.list = async_to_streamed_response_wrapper(routes_for_location.list)
