# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ScheduleForRouteRetrieveResponse

__all__ = ["ScheduleForRouteResource", "AsyncScheduleForRouteResource"]


class ScheduleForRouteResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ScheduleForRouteResourceWithRawResponse:
        return ScheduleForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ScheduleForRouteResourceWithStreamingResponse:
        return ScheduleForRouteResourceWithStreamingResponse(self)

    def retrieve(
        self,
        route_id: str,
        *,
        date: date | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ScheduleForRouteRetrieveResponse:
        """Retrieve the full schedule for a route on a particular day"""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        _params = {
            "date": date,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/schedule-for-route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ScheduleForRouteRetrieveResponse,
        )


class AsyncScheduleForRouteResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncScheduleForRouteResourceWithRawResponse:
        return AsyncScheduleForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncScheduleForRouteResourceWithStreamingResponse:
        return AsyncScheduleForRouteResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        route_id: str,
        *,
        date: date | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ScheduleForRouteRetrieveResponse:
        """Retrieve the full schedule for a route on a particular day"""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        _params = {
            "date": date,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/schedule-for-route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ScheduleForRouteRetrieveResponse,
        )


class ScheduleForRouteResourceWithRawResponse:
    def __init__(self, schedule_for_route: ScheduleForRouteResource) -> None:
        self.retrieve = to_raw_response_wrapper(schedule_for_route.retrieve)


class AsyncScheduleForRouteResourceWithRawResponse:
    def __init__(self, schedule_for_route: AsyncScheduleForRouteResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(schedule_for_route.retrieve)


class ScheduleForRouteResourceWithStreamingResponse:
    def __init__(self, schedule_for_route: ScheduleForRouteResource) -> None:
        self.retrieve = to_streamed_response_wrapper(schedule_for_route.retrieve)


class AsyncScheduleForRouteResourceWithStreamingResponse:
    def __init__(self, schedule_for_route: AsyncScheduleForRouteResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(schedule_for_route.retrieve)
