# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ScheduleForStopRetrieveResponse

__all__ = ["ScheduleForStopResource", "AsyncScheduleForStopResource"]


class ScheduleForStopResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ScheduleForStopResourceWithRawResponse:
        return ScheduleForStopResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ScheduleForStopResourceWithStreamingResponse:
        return ScheduleForStopResourceWithStreamingResponse(self)

    def retrieve(
        self,
        stop_id: str,
        *,
        date: date | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ScheduleForStopRetrieveResponse:
        """Get schedule for a specific stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "date": date,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/schedule-for-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ScheduleForStopRetrieveResponse,
        )


class AsyncScheduleForStopResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncScheduleForStopResourceWithRawResponse:
        return AsyncScheduleForStopResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncScheduleForStopResourceWithStreamingResponse:
        return AsyncScheduleForStopResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        stop_id: str,
        *,
        date: date | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ScheduleForStopRetrieveResponse:
        """Get schedule for a specific stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        _params = {
            "date": date,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/schedule-for-stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=ScheduleForStopRetrieveResponse,
        )


class ScheduleForStopResourceWithRawResponse:
    def __init__(self, schedule_for_stop: ScheduleForStopResource) -> None:
        self.retrieve = to_raw_response_wrapper(schedule_for_stop.retrieve)


class AsyncScheduleForStopResourceWithRawResponse:
    def __init__(self, schedule_for_stop: AsyncScheduleForStopResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(schedule_for_stop.retrieve)


class ScheduleForStopResourceWithStreamingResponse:
    def __init__(self, schedule_for_stop: ScheduleForStopResource) -> None:
        self.retrieve = to_streamed_response_wrapper(schedule_for_stop.retrieve)


class AsyncScheduleForStopResourceWithStreamingResponse:
    def __init__(self, schedule_for_stop: AsyncScheduleForStopResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(schedule_for_stop.retrieve)
