# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import SearchForRouteListResponse

__all__ = ["SearchForRouteResource", "AsyncSearchForRouteResource"]


class SearchForRouteResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> SearchForRouteResourceWithRawResponse:
        return SearchForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> SearchForRouteResourceWithStreamingResponse:
        return SearchForRouteResourceWithStreamingResponse(self)

    def list(
        self,
        *,
        input: str | NotGiven = not_given,
        max_count: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> SearchForRouteListResponse:
        """Search for a route based on its name."""
        _params = {
            "input": input,
            "maxCount": max_count,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/search/route.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=SearchForRouteListResponse,
        )


class AsyncSearchForRouteResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncSearchForRouteResourceWithRawResponse:
        return AsyncSearchForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncSearchForRouteResourceWithStreamingResponse:
        return AsyncSearchForRouteResourceWithStreamingResponse(self)

    async def list(
        self,
        *,
        input: str | NotGiven = not_given,
        max_count: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> SearchForRouteListResponse:
        """Search for a route based on its name."""
        _params = {
            "input": input,
            "maxCount": max_count,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/search/route.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=SearchForRouteListResponse,
        )


class SearchForRouteResourceWithRawResponse:
    def __init__(self, search_for_route: SearchForRouteResource) -> None:
        self.list = to_raw_response_wrapper(search_for_route.list)


class AsyncSearchForRouteResourceWithRawResponse:
    def __init__(self, search_for_route: AsyncSearchForRouteResource) -> None:
        self.list = async_to_raw_response_wrapper(search_for_route.list)


class SearchForRouteResourceWithStreamingResponse:
    def __init__(self, search_for_route: SearchForRouteResource) -> None:
        self.list = to_streamed_response_wrapper(search_for_route.list)


class AsyncSearchForRouteResourceWithStreamingResponse:
    def __init__(self, search_for_route: AsyncSearchForRouteResource) -> None:
        self.list = async_to_streamed_response_wrapper(search_for_route.list)
