# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import ShapeRetrieveResponse

__all__ = ["ShapeResource", "AsyncShapeResource"]


class ShapeResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ShapeResourceWithRawResponse:
        return ShapeResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ShapeResourceWithStreamingResponse:
        return ShapeResourceWithStreamingResponse(self)

    def retrieve(
        self,
        shape_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ShapeRetrieveResponse:
        """Retrieve a shape (the path traveled by a transit vehicle) by ID."""
        if not shape_id:
            raise ValueError(
                f"Expected a non-empty value for `shape_id` but received {shape_id!r}"
            )
        return self._get(
            f"/api/where/shape/{shape_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=ShapeRetrieveResponse,
        )


class AsyncShapeResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncShapeResourceWithRawResponse:
        return AsyncShapeResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncShapeResourceWithStreamingResponse:
        return AsyncShapeResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        shape_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ShapeRetrieveResponse:
        """Retrieve a shape (the path traveled by a transit vehicle) by ID."""
        if not shape_id:
            raise ValueError(
                f"Expected a non-empty value for `shape_id` but received {shape_id!r}"
            )
        return await self._get(
            f"/api/where/shape/{shape_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=ShapeRetrieveResponse,
        )


class ShapeResourceWithRawResponse:
    def __init__(self, shape: ShapeResource) -> None:
        self.retrieve = to_raw_response_wrapper(shape.retrieve)


class AsyncShapeResourceWithRawResponse:
    def __init__(self, shape: AsyncShapeResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(shape.retrieve)


class ShapeResourceWithStreamingResponse:
    def __init__(self, shape: ShapeResource) -> None:
        self.retrieve = to_streamed_response_wrapper(shape.retrieve)


class AsyncShapeResourceWithStreamingResponse:
    def __init__(self, shape: AsyncShapeResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(shape.retrieve)
