# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import StopsForRouteListResponse

__all__ = ["StopsForRouteResource", "AsyncStopsForRouteResource"]


class StopsForRouteResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> StopsForRouteResourceWithRawResponse:
        return StopsForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> StopsForRouteResourceWithStreamingResponse:
        return StopsForRouteResourceWithStreamingResponse(self)

    def list(
        self,
        route_id: str,
        *,
        include_polylines: bool | NotGiven = not_given,
        time: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> StopsForRouteListResponse:
        """Get stops for a specific route"""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        _params = {
            "includePolylines": include_polylines,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/stops-for-route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=StopsForRouteListResponse,
        )


class AsyncStopsForRouteResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncStopsForRouteResourceWithRawResponse:
        return AsyncStopsForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncStopsForRouteResourceWithStreamingResponse:
        return AsyncStopsForRouteResourceWithStreamingResponse(self)

    async def list(
        self,
        route_id: str,
        *,
        include_polylines: bool | NotGiven = not_given,
        time: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> StopsForRouteListResponse:
        """Get stops for a specific route"""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        _params = {
            "includePolylines": include_polylines,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/stops-for-route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=StopsForRouteListResponse,
        )


class StopsForRouteResourceWithRawResponse:
    def __init__(self, stops_for_route: StopsForRouteResource) -> None:
        self.list = to_raw_response_wrapper(stops_for_route.list)


class AsyncStopsForRouteResourceWithRawResponse:
    def __init__(self, stops_for_route: AsyncStopsForRouteResource) -> None:
        self.list = async_to_raw_response_wrapper(stops_for_route.list)


class StopsForRouteResourceWithStreamingResponse:
    def __init__(self, stops_for_route: StopsForRouteResource) -> None:
        self.list = to_streamed_response_wrapper(stops_for_route.list)


class AsyncStopsForRouteResourceWithStreamingResponse:
    def __init__(self, stops_for_route: AsyncStopsForRouteResource) -> None:
        self.list = async_to_streamed_response_wrapper(stops_for_route.list)
