# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import StopIDsForAgencyListResponse

__all__ = ["StopIDsForAgencyResource", "AsyncStopIDsForAgencyResource"]


class StopIDsForAgencyResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> StopIDsForAgencyResourceWithRawResponse:
        return StopIDsForAgencyResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> StopIDsForAgencyResourceWithStreamingResponse:
        return StopIDsForAgencyResourceWithStreamingResponse(self)

    def list(
        self,
        agency_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> StopIDsForAgencyListResponse:
        """Get stop IDs for a specific agency"""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        return self._get(
            f"/api/where/stop-ids-for-agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=StopIDsForAgencyListResponse,
        )


class AsyncStopIDsForAgencyResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncStopIDsForAgencyResourceWithRawResponse:
        return AsyncStopIDsForAgencyResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncStopIDsForAgencyResourceWithStreamingResponse:
        return AsyncStopIDsForAgencyResourceWithStreamingResponse(self)

    async def list(
        self,
        agency_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> StopIDsForAgencyListResponse:
        """Get stop IDs for a specific agency"""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        return await self._get(
            f"/api/where/stop-ids-for-agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=StopIDsForAgencyListResponse,
        )


class StopIDsForAgencyResourceWithRawResponse:
    def __init__(self, stop_ids_for_agency: StopIDsForAgencyResource) -> None:
        self.list = to_raw_response_wrapper(stop_ids_for_agency.list)


class AsyncStopIDsForAgencyResourceWithRawResponse:
    def __init__(self, stop_ids_for_agency: AsyncStopIDsForAgencyResource) -> None:
        self.list = async_to_raw_response_wrapper(stop_ids_for_agency.list)


class StopIDsForAgencyResourceWithStreamingResponse:
    def __init__(self, stop_ids_for_agency: StopIDsForAgencyResource) -> None:
        self.list = to_streamed_response_wrapper(stop_ids_for_agency.list)


class AsyncStopIDsForAgencyResourceWithStreamingResponse:
    def __init__(self, stop_ids_for_agency: AsyncStopIDsForAgencyResource) -> None:
        self.list = async_to_streamed_response_wrapper(stop_ids_for_agency.list)
