# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import StopRetrieveResponse

__all__ = ["StopResource", "AsyncStopResource"]


class StopResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> StopResourceWithRawResponse:
        return StopResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> StopResourceWithStreamingResponse:
        return StopResourceWithStreamingResponse(self)

    def retrieve(
        self,
        stop_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> StopRetrieveResponse:
        """Get details of a specific stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        return self._get(
            f"/api/where/stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=StopRetrieveResponse,
        )


class AsyncStopResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncStopResourceWithRawResponse:
        return AsyncStopResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncStopResourceWithStreamingResponse:
        return AsyncStopResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        stop_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> StopRetrieveResponse:
        """Get details of a specific stop"""
        if not stop_id:
            raise ValueError(
                f"Expected a non-empty value for `stop_id` but received {stop_id!r}"
            )
        return await self._get(
            f"/api/where/stop/{stop_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=StopRetrieveResponse,
        )


class StopResourceWithRawResponse:
    def __init__(self, stop: StopResource) -> None:
        self.retrieve = to_raw_response_wrapper(stop.retrieve)


class AsyncStopResourceWithRawResponse:
    def __init__(self, stop: AsyncStopResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(stop.retrieve)


class StopResourceWithStreamingResponse:
    def __init__(self, stop: StopResource) -> None:
        self.retrieve = to_streamed_response_wrapper(stop.retrieve)


class AsyncStopResourceWithStreamingResponse:
    def __init__(self, stop: AsyncStopResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(stop.retrieve)
