# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import Trip, TripDetailRetrieveResponse

__all__ = ["TripDetailsResource", "AsyncTripDetailsResource"]


class TripDetailsResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> TripDetailsResourceWithRawResponse:
        return TripDetailsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> TripDetailsResourceWithStreamingResponse:
        return TripDetailsResourceWithStreamingResponse(self)

    def retrieve(
        self,
        trip_id: str,
        *,
        service_date: int | NotGiven = not_given,
        include_trip: bool | NotGiven = not_given,
        include_schedule: bool | NotGiven = not_given,
        include_status: bool | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TripDetailRetrieveResponse:
        """Retrieve Trip Details"""
        if not trip_id:
            raise ValueError(
                f"Expected a non-empty value for `trip_id` but received {trip_id!r}"
            )
        _params = {
            "serviceDate": service_date,
            "includeTrip": include_trip,
            "includeSchedule": include_schedule,
            "includeStatus": include_status,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/trip-details/{trip_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=TripDetailRetrieveResponse,
        )


class AsyncTripDetailsResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncTripDetailsResourceWithRawResponse:
        return AsyncTripDetailsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncTripDetailsResourceWithStreamingResponse:
        return AsyncTripDetailsResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        trip_id: str,
        *,
        service_date: int | NotGiven = not_given,
        include_trip: bool | NotGiven = not_given,
        include_schedule: bool | NotGiven = not_given,
        include_status: bool | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TripDetailRetrieveResponse:
        """Retrieve Trip Details"""
        if not trip_id:
            raise ValueError(
                f"Expected a non-empty value for `trip_id` but received {trip_id!r}"
            )
        _params = {
            "serviceDate": service_date,
            "includeTrip": include_trip,
            "includeSchedule": include_schedule,
            "includeStatus": include_status,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/trip-details/{trip_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=TripDetailRetrieveResponse,
        )


class TripDetailsResourceWithRawResponse:
    def __init__(self, trip_details: TripDetailsResource) -> None:
        self.retrieve = to_raw_response_wrapper(trip_details.retrieve)


class AsyncTripDetailsResourceWithRawResponse:
    def __init__(self, trip_details: AsyncTripDetailsResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(trip_details.retrieve)


class TripDetailsResourceWithStreamingResponse:
    def __init__(self, trip_details: TripDetailsResource) -> None:
        self.retrieve = to_streamed_response_wrapper(trip_details.retrieve)


class AsyncTripDetailsResourceWithStreamingResponse:
    def __init__(self, trip_details: AsyncTripDetailsResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(trip_details.retrieve)
