# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import TripsForRouteListResponse

__all__ = ["TripsForRouteResource", "AsyncTripsForRouteResource"]


class TripsForRouteResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> TripsForRouteResourceWithRawResponse:
        return TripsForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> TripsForRouteResourceWithStreamingResponse:
        return TripsForRouteResourceWithStreamingResponse(self)

    def list(
        self,
        route_id: str,
        *,
        include_status: bool | NotGiven = not_given,
        include_schedule: bool | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TripsForRouteListResponse:
        """Search for active trips for a specific route."""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        _params = {
            "includeStatus": include_status,
            "includeSchedule": include_schedule,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/trips-for-route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=TripsForRouteListResponse,
        )


class AsyncTripsForRouteResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncTripsForRouteResourceWithRawResponse:
        return AsyncTripsForRouteResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncTripsForRouteResourceWithStreamingResponse:
        return AsyncTripsForRouteResourceWithStreamingResponse(self)

    async def list(
        self,
        route_id: str,
        *,
        include_status: bool | NotGiven = not_given,
        include_schedule: bool | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TripsForRouteListResponse:
        """Search for active trips for a specific route."""
        if not route_id:
            raise ValueError(
                f"Expected a non-empty value for `route_id` but received {route_id!r}"
            )
        _params = {
            "includeStatus": include_status,
            "includeSchedule": include_schedule,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/trips-for-route/{route_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=TripsForRouteListResponse,
        )


class TripsForRouteResourceWithRawResponse:
    def __init__(self, trips_for_route: TripsForRouteResource) -> None:
        self.list = to_raw_response_wrapper(trips_for_route.list)


class AsyncTripsForRouteResourceWithRawResponse:
    def __init__(self, trips_for_route: AsyncTripsForRouteResource) -> None:
        self.list = async_to_raw_response_wrapper(trips_for_route.list)


class TripsForRouteResourceWithStreamingResponse:
    def __init__(self, trips_for_route: TripsForRouteResource) -> None:
        self.list = to_streamed_response_wrapper(trips_for_route.list)


class AsyncTripsForRouteResourceWithStreamingResponse:
    def __init__(self, trips_for_route: AsyncTripsForRouteResource) -> None:
        self.list = async_to_streamed_response_wrapper(trips_for_route.list)
