# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import TripsForLocationListResponse

__all__ = ["TripsForLocationResource", "AsyncTripsForLocationResource"]


class TripsForLocationResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> TripsForLocationResourceWithRawResponse:
        return TripsForLocationResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> TripsForLocationResourceWithStreamingResponse:
        return TripsForLocationResourceWithStreamingResponse(self)

    def list(
        self,
        *,
        lat: float | NotGiven = not_given,
        lon: float | NotGiven = not_given,
        lat_span: float | NotGiven = not_given,
        lon_span: float | NotGiven = not_given,
        include_trip: bool | NotGiven = not_given,
        include_schedule: bool | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TripsForLocationListResponse:
        """Retrieve trips for a given location"""
        _params = {
            "lat": lat,
            "lon": lon,
            "latSpan": lat_span,
            "lonSpan": lon_span,
            "includeTrip": include_trip,
            "includeSchedule": include_schedule,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/trips-for-location.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=TripsForLocationListResponse,
        )


class AsyncTripsForLocationResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncTripsForLocationResourceWithRawResponse:
        return AsyncTripsForLocationResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncTripsForLocationResourceWithStreamingResponse:
        return AsyncTripsForLocationResourceWithStreamingResponse(self)

    async def list(
        self,
        *,
        lat: float | NotGiven = not_given,
        lon: float | NotGiven = not_given,
        lat_span: float | NotGiven = not_given,
        lon_span: float | NotGiven = not_given,
        include_trip: bool | NotGiven = not_given,
        include_schedule: bool | NotGiven = not_given,
        time: int | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TripsForLocationListResponse:
        """Retrieve trips for a given location"""
        _params = {
            "lat": lat,
            "lon": lon,
            "latSpan": lat_span,
            "lonSpan": lon_span,
            "includeTrip": include_trip,
            "includeSchedule": include_schedule,
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/trips-for-location.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=TripsForLocationListResponse,
        )


class TripsForLocationResourceWithRawResponse:
    def __init__(self, trips_for_location: TripsForLocationResource) -> None:
        self.list = to_raw_response_wrapper(trips_for_location.list)


class AsyncTripsForLocationResourceWithRawResponse:
    def __init__(self, trips_for_location: AsyncTripsForLocationResource) -> None:
        self.list = async_to_raw_response_wrapper(trips_for_location.list)


class TripsForLocationResourceWithStreamingResponse:
    def __init__(self, trips_for_location: TripsForLocationResource) -> None:
        self.list = to_streamed_response_wrapper(trips_for_location.list)


class AsyncTripsForLocationResourceWithStreamingResponse:
    def __init__(self, trips_for_location: AsyncTripsForLocationResource) -> None:
        self.list = async_to_streamed_response_wrapper(trips_for_location.list)
