# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from onebusaway._core._request_options import make_request_options
from onebusaway._core._resource import AsyncAPIResource, SyncAPIResource
from onebusaway._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from onebusaway._core._sentinels import NotGiven, not_given
from onebusaway._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from onebusaway.types import VehiclesForAgencyListResponse

__all__ = ["VehiclesForAgencyResource", "AsyncVehiclesForAgencyResource"]


class VehiclesForAgencyResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> VehiclesForAgencyResourceWithRawResponse:
        return VehiclesForAgencyResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> VehiclesForAgencyResourceWithStreamingResponse:
        return VehiclesForAgencyResourceWithStreamingResponse(self)

    def list(
        self,
        agency_id: str,
        *,
        time: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> VehiclesForAgencyListResponse:
        """Get vehicles for a specific agency"""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        _params = {
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return self._get(
            f"/api/where/vehicles-for-agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=VehiclesForAgencyListResponse,
        )


class AsyncVehiclesForAgencyResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncVehiclesForAgencyResourceWithRawResponse:
        return AsyncVehiclesForAgencyResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncVehiclesForAgencyResourceWithStreamingResponse:
        return AsyncVehiclesForAgencyResourceWithStreamingResponse(self)

    async def list(
        self,
        agency_id: str,
        *,
        time: str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> VehiclesForAgencyListResponse:
        """Get vehicles for a specific agency"""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        _params = {
            "time": time,
        }
        _params = {k: v for k, v in _params.items() if v is not not_given}
        return await self._get(
            f"/api/where/vehicles-for-agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                params=_params,
            ),
            cast_to=VehiclesForAgencyListResponse,
        )


class VehiclesForAgencyResourceWithRawResponse:
    def __init__(self, vehicles_for_agency: VehiclesForAgencyResource) -> None:
        self.list = to_raw_response_wrapper(vehicles_for_agency.list)


class AsyncVehiclesForAgencyResourceWithRawResponse:
    def __init__(self, vehicles_for_agency: AsyncVehiclesForAgencyResource) -> None:
        self.list = async_to_raw_response_wrapper(vehicles_for_agency.list)


class VehiclesForAgencyResourceWithStreamingResponse:
    def __init__(self, vehicles_for_agency: VehiclesForAgencyResource) -> None:
        self.list = to_streamed_response_wrapper(vehicles_for_agency.list)


class AsyncVehiclesForAgencyResourceWithStreamingResponse:
    def __init__(self, vehicles_for_agency: AsyncVehiclesForAgencyResource) -> None:
        self.list = async_to_streamed_response_wrapper(vehicles_for_agency.list)
