"""MCP server emitter — `stainful mcp` (DESIGN §5b extension).

Generates `<pkg>/mcp_server.py` inside an already-generated SDK directory.
Each HTTP-endpoint Method becomes one MCP tool (`<resource_chain>_<method>`,
e.g. `chat_completions_create`); webhook-unwrap methods are skipped (no
remote call). Authentication and runtime are entirely the generated
SDK's job — the MCP server is a thin adapter over the SDK's instance
methods.

Wire transport = stdio (canonical MCP transport; usable from Claude
Desktop, Cline, Continue, mcp-cli, etc.). The runtime uses the official
`mcp` Python package — declared as a separate optional dependency so
plain SDK users don't pull it in.

Honest v1 scope:
  - One tool per HTTP-method Method (verb is encoded in the dispatch)
  - inputSchema is a faithful JSON Schema of the method's arguments
    (path params, query params, body if object-shaped → expanded;
    binary/multipart bodies → `{type: string, format: binary}`)
  - Response serialized as `TextContent` (JSON-stringified) — the
    MCP client (often an LLM) consumes that
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from stainful.emit.python._casing import brand, package, snake
from stainful.ir.model import (
    API,
    ContentType,
    Method,
    Resource,
)
from stainful.ir.types import (
    AnyType,
    ArrayType,
    EnumType,
    MapType,
    ModelRef,
    NullType,
    ObjectType,
    PrimitiveKind,
    PrimitiveType,
    Property,
    Type,
    UnionType,
)


def emit_mcp(api: API, out_path: str) -> None:
    """Emit a single-file MCP server at `out_path`. The file expects the
    matching generated SDK to be importable (typical placement is
    `<sdk_dir>/<pkg>/mcp_server.py`).
    """
    src = _MCPEmitter(api).render()
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(src)


class _MCPEmitter:
    def __init__(self, api: API) -> None:
        self.api = api
        self.pkg = package(api.name)
        self.brand = brand(api.name)

    def render(self) -> str:
        tools = self._collect_tools()
        tool_defs = ",\n".join(_python_repr_tool(t) for t in tools)
        dispatch_arms = "\n".join(
            _dispatch_arm(t["meta"]) for t in tools
        )
        return _TEMPLATE.format(
            pkg=self.pkg,
            brand=self.brand,
            tool_defs=tool_defs,
            dispatch_arms=dispatch_arms,
            num_tools=len(tools),
        )

    # ----- collection -------------------------------------------------------
    def _collect_tools(self) -> list[dict]:
        """Walk the resource tree → flat list of tool descriptors."""
        out: list[dict] = []
        self._walk(self.api.root.subresources, [], out)
        return out

    def _walk(
        self, resources: list[Resource], chain: list[str], out: list[dict]
    ) -> None:
        for r in resources:
            new_chain = chain + [snake(r.name)]
            for m in r.methods:
                # Skip webhook_unwrap — those don't make remote calls and
                # don't fit the MCP "call a tool, get a result" mental model.
                if m.emit_hints.get("type") == "webhook_unwrap":
                    continue
                out.append(self._build_tool(m, new_chain))
            self._walk(r.subresources, new_chain, out)

    def _build_tool(self, m: Method, chain: list[str]) -> dict:
        tool_name = "_".join(chain + [snake(m.name)])
        description = (m.docs or "").strip() or (
            f"{m.http_verb.value.upper()} {m.path}" if m.path
            else f"{tool_name} (generated by stainful)"
        )
        properties: dict[str, Any] = {}
        required: list[str] = []
        for p in m.path_params:
            properties[snake(p.name)] = self._schema_with_description(p)
            required.append(snake(p.name))
        for p in m.query_params:
            properties[snake(p.name)] = self._schema_with_description(p)
            if p.required:
                required.append(snake(p.name))
        # Body: if object-shaped + JSON, expand its top-level properties as
        # peers (matches the generated Python signature). Otherwise (binary,
        # opaque), expose a single `body` field.
        if m.body is not None:
            if (
                m.body.content_type in (ContentType.JSON, ContentType.MULTIPART)
                and _is_object_like(m.body.type, self.api)
            ):
                obj = _resolve_object(m.body.type, self.api)
                if obj is not None:
                    for p in obj.properties:
                        properties[snake(p.name)] = self._schema_with_description(p)
                        if p.required:
                            required.append(snake(p.name))
            else:
                properties["body"] = self._schema(m.body.type)
                if m.body.required:
                    required.append("body")
        input_schema: dict[str, Any] = {
            "type": "object",
            "properties": properties,
        }
        if required:
            input_schema["required"] = sorted(set(required))
        return {
            "tool": {
                "name": tool_name,
                "description": description,
                "inputSchema": input_schema,
            },
            "meta": {
                "tool_name": tool_name,
                "chain": chain,
                "method": snake(m.name),
                # split positional path-arg names so we can call the SDK with them
                "path_args": [snake(p.name) for p in m.path_params],
                # signal so dispatch doesn't try to access webhook attrs
                "is_streaming": m.streaming is not None,
            },
        }

    # ----- IR.Type → JSON Schema -------------------------------------------
    def _schema_with_description(self, p: Property) -> dict[str, Any]:
        s = self._schema(p.type)
        if p.docs:
            s = {"description": p.docs.strip(), **s}
        if p.nullable and "type" in s and isinstance(s["type"], str):
            # JSON Schema 2020-12 allows `type: [..., "null"]`. Mintlify /
            # MCP clients all accept this.
            s = {**s, "type": [s["type"], "null"]}
        return s

    def _schema(self, t: Type) -> dict[str, Any]:
        if isinstance(t, PrimitiveType):
            base = {
                PrimitiveKind.STRING: "string",
                PrimitiveKind.INTEGER: "integer",
                PrimitiveKind.NUMBER: "number",
                PrimitiveKind.BOOLEAN: "boolean",
                PrimitiveKind.BYTES: "string",          # base64-encoded
                PrimitiveKind.DATE: "string",
                PrimitiveKind.DATETIME: "string",
                PrimitiveKind.DECIMAL: "string",
                PrimitiveKind.UUID: "string",
            }.get(t.kind, "string")
            out: dict[str, Any] = {"type": base}
            if t.kind == PrimitiveKind.BYTES:
                out["format"] = "binary"
            elif t.kind == PrimitiveKind.DATE:
                out["format"] = "date"
            elif t.kind == PrimitiveKind.DATETIME:
                out["format"] = "date-time"
            elif t.kind == PrimitiveKind.UUID:
                out["format"] = "uuid"
            return out
        if isinstance(t, NullType):
            return {"type": "null"}
        if isinstance(t, AnyType):
            return {}
        if isinstance(t, EnumType):
            return {"enum": [m.value for m in t.members]}
        if isinstance(t, ArrayType):
            return {"type": "array", "items": self._schema(t.item)}
        if isinstance(t, MapType):
            return {
                "type": "object",
                "additionalProperties": self._schema(t.value),
            }
        if isinstance(t, UnionType):
            return {"anyOf": [self._schema(v) for v in t.variants]}
        if isinstance(t, ModelRef):
            comp = self.api.models.get(t.name)
            if comp is not None and isinstance(comp.type, ObjectType):
                return self._object_schema(comp.type)
            return {}
        if isinstance(t, ObjectType):
            return self._object_schema(t)
        return {}

    def _object_schema(self, obj: ObjectType) -> dict[str, Any]:
        props: dict[str, Any] = {}
        req: list[str] = []
        for p in obj.properties:
            props[p.name] = self._schema(p.type)
            if p.required:
                req.append(p.name)
        out: dict[str, Any] = {"type": "object", "properties": props}
        if req:
            out["required"] = req
        return out


# ----- helpers --------------------------------------------------------------
def _resolve_object(t: Type, api: API):
    if isinstance(t, ObjectType):
        return t
    if isinstance(t, ModelRef):
        comp = api.models.get(t.name)
        if comp is not None and isinstance(comp.type, ObjectType):
            return comp.type
    return None


def _is_object_like(t: Type, api: API) -> bool:
    return _resolve_object(t, api) is not None


def _python_repr_tool(t: dict) -> str:
    """Render a Tool literal as Python source — readable and stable
    (deterministic ordering inside the JSON Schema)."""
    spec = t["tool"]
    schema_str = json.dumps(spec["inputSchema"], indent=8, sort_keys=True)
    # bump indent on continuation lines from 8 → outer alignment
    schema_indented = "\n".join(
        "        " + line if i > 0 else line
        for i, line in enumerate(schema_str.splitlines())
    )
    description = spec["description"].replace('"""', "'''")
    return (
        "    Tool(\n"
        f"        name={spec['name']!r},\n"
        f"        description={description!r},\n"
        f"        inputSchema={schema_indented},\n"
        "    )"
    )


def _dispatch_arm(meta: dict) -> str:
    """Generate `if name == "<tool>": …` branch for `call_tool`."""
    tool_name = meta["tool_name"]
    chain = meta["chain"]
    method = meta["method"]
    path_args = meta["path_args"]
    accessor = "_client()." + ".".join(chain) + f".{method}"
    if path_args:
        # call with path args by name first, then **rest
        pop_lines = "\n".join(
            f'        {a} = arguments.pop({a!r})' for a in path_args
        )
        positional = ", ".join(path_args)
        call = (
            f"{pop_lines}\n"
            f"        result = {accessor}({positional}, **arguments)"
        )
    else:
        call = f"        result = {accessor}(**arguments)"
    return (
        f'    if name == {tool_name!r}:\n'
        f"{call}\n"
        f"        return [TextContent(type='text', text=_to_text(result))]"
    )


_TEMPLATE = '''# File generated by stainful — DO NOT EDIT.
"""{pkg} MCP server — generated by stainful.

Exposes the generated {pkg} SDK as a Model Context Protocol (MCP) server
over stdio. Run it under any MCP client (Claude Desktop, Cline, mcp-cli,
…):

    python -m {pkg}.mcp_server

Authentication is exactly the SDK's: the {brand} client picks up its
configured env var on construction. {num_tools} tools are exposed
(one per HTTP method).
"""

from __future__ import annotations

import asyncio
import json
from typing import Any

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

from . import {brand}

_app: Server = Server({pkg!r})
_client_singleton: {brand} | None = None


def _client() -> {brand}:
    """Lazy-construct the SDK client on first tool call. Defers the
    `api_key` check (and env-var lookup) until the MCP server is
    actually invoked — so the module imports cleanly in tooling that
    only enumerates available servers."""
    global _client_singleton
    if _client_singleton is None:
        _client_singleton = {brand}()
    return _client_singleton


def _to_text(result: Any) -> str:
    """Serialize an SDK return value (pydantic model / bytes / page / …)
    as a single text payload for MCP clients."""
    if isinstance(result, bytes):
        # Binary download — return base64 + a hint.
        import base64
        return json.dumps({{
            "_kind": "binary",
            "base64": base64.b64encode(result).decode(),
        }})
    if hasattr(result, "model_dump_json"):
        return result.model_dump_json()
    if hasattr(result, "__iter__") and not isinstance(result, (str, bytes)):
        # Paginated page — eagerly walk it (synchronously). Caller can
        # always set per_page/limit on the input if they want a slice.
        items: list = []
        for it in result:
            items.append(
                it.model_dump() if hasattr(it, "model_dump") else it
            )
        return json.dumps(items, default=str)
    return json.dumps(result, default=str)


@_app.list_tools()
async def list_tools() -> list[Tool]:
    return [
{tool_defs}
    ]


@_app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    arguments = dict(arguments or {{}})    # local copy; we may .pop() from it
    # `result` is intentionally untyped — each dispatch arm assigns a
    # different concrete response model, and we serialize via `_to_text`
    # before returning, so the loose typing is contained.
    result: Any
{dispatch_arms}
    raise ValueError(f"Unknown tool: {{name!r}}")


async def main() -> None:
    async with stdio_server() as (read, write):
        await _app.run(read, write, _app.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
'''
