"""Markdown docs emitter — `stainful docs` (DESIGN §5b extension).

Same IR, different renderer. Emits a single `api.md` per the Stainless
convention (oracle: `tests/oracles/openai-python/api.md`):

  # Resource
  Methods:
    - <code title="<verb> <path>">client.<chain>.<method>(...) -> <Type></code>
  ## Subresource
    - ...

Mintlify-compatible by virtue of being valid Markdown + inline HTML
links. Generated SDK file paths (`./src/<pkg>/resources/<...>.py`) link
back into the SDK tree stainful itself just generated.
"""

from __future__ import annotations

from pathlib import Path

from stainful.emit.python._casing import (
    package,
    pascal,
    pascal_singular_last,
    set_user_casings,
    snake,
)
from stainful.ir.model import API, Method, Resource
from stainful.ir.types import (
    AnyType,
    ArrayType,
    ModelRef,
    ObjectType,
    PrimitiveKind,
    PrimitiveType,
    Type,
    UnionType,
)


def emit_docs(api: API, out_path: str) -> None:
    """Emit a single Markdown file at `out_path` documenting the API surface."""
    md = _DocsEmitter(api).render()
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(md)


class _DocsEmitter:
    def __init__(self, api: API) -> None:
        set_user_casings(api.custom_casings)
        self.api = api
        self.pkg = api.python_package_name or package(api.name)

    # ----- top-level render -------------------------------------------------
    def render(self) -> str:
        sections: list[str] = [
            f"# {self.pkg}",
            "",
            f"Generated by [stainful](https://github.com/stainlu/stainful) "
            f"from `{self.api.name}`'s OpenAPI spec + `stainless.yml`. "
            f"Drop-in for Stainless-generated SDKs.",
            "",
        ]
        if self.api.shared_models:
            sections += self._shared_types_block()
        for r in self.api.root.subresources:
            sections += self._resource_block(r, depth=1, parent_path=(), chain=())
        # Trailing newline only (single blank not multi).
        return "\n".join(sections).rstrip() + "\n"

    # ----- per-section renderers --------------------------------------------
    def _shared_types_block(self) -> list[str]:
        names = sorted({pascal(key) for key in self.api.shared_models.values()})
        if not names:
            return []
        names_str = ",\n    ".join(names)
        return [
            "# Shared Types",
            "",
            "```python",
            f"from {self.pkg}.types import (",
            f"    {names_str},",
            ")",
            "```",
            "",
        ]

    def _resource_block(
        self,
        r: Resource,
        *,
        depth: int,
        parent_path: tuple[str, ...],
        chain: tuple[str, ...],
    ) -> list[str]:
        hashes = "#" * depth
        heading = pascal(r.name)
        access_chain = chain + (snake(r.name),)
        # File path of the resource module in the generated SDK (matches
        # the nested layout the Python emitter writes).
        resource_path = self._resource_file_path(r, parent_path)
        out: list[str] = [f"{hashes} {heading}", ""]
        # Types block — list named models the resource's methods reference
        # (matches openai-python's api.md format). Only emit when there's
        # something to import.
        types = self._collect_resource_types(r, access_chain)
        if types:
            out += [
                "Types:",
                "",
                "```python",
                f"from {self.pkg}.types import {', '.join(types)}",
                "```",
                "",
            ]
        if r.methods:
            out.append("Methods:")
            out.append("")
            for m in r.methods:
                out.append(
                    "- " + self._method_line(m, access_chain, resource_path)
                )
            out.append("")
        # subresources nest one level deeper
        sub_parent = parent_path + (snake(r.name),) if r.subresources else parent_path
        for sub in r.subresources:
            out += self._resource_block(
                sub,
                depth=depth + 1,
                parent_path=sub_parent,
                chain=access_chain,
            )
        return out

    def _collect_resource_types(
        self, r: Resource, access_chain: tuple[str, ...],
    ) -> list[str]:
        """Walk each method's return/body/params types; collect the
        ModelRef names that appear in the public surface so they can be
        imported in a per-resource Types: block (openai-python style).
        Inline ObjectType responses use the path-named class — also
        included. Sorted + deduped.
        """
        out: set[str] = set()
        for m in r.methods:
            for status in ("200", "201", "2XX", "default"):
                if status in m.responses:
                    t = m.responses[status]
                    if isinstance(t, ModelRef):
                        out.add(pascal(t.name))
                    elif isinstance(t, ObjectType):
                        out.add(
                            f"{pascal_singular_last(access_chain[-1])}"
                            f"{pascal(m.name)}Response"
                        )
                    break
            if m.body is not None:
                # Body params class
                out.add(
                    f"{pascal_singular_last(access_chain[-1])}"
                    f"{pascal(m.name)}Params"
                )
        return sorted(out)

    # ----- per-method line --------------------------------------------------
    def _method_line(
        self,
        m: Method,
        access_chain: tuple[str, ...],
        resource_file: str,
    ) -> str:
        verb = m.http_verb.value
        if m.emit_hints.get("type") == "webhook_unwrap":
            # No HTTP call; render w/o the `<code title=...>` verb/path part.
            sig = self._method_signature(m, access_chain, resource_file)
            ret = "EventUnion"
            return f"`client.{'.'.join(access_chain)}.{m.name}(...) -> {ret}`"
        sig = self._method_signature(m, access_chain, resource_file)
        ret_link = self._return_link(m, access_chain)
        # The opening tag includes the wire verb + path so users can grep.
        return (
            f'<code title="{verb} {m.path}">'
            f"{sig} -> {ret_link}"
            f"</code>"
        )

    def _method_signature(
        self,
        m: Method,
        access_chain: tuple[str, ...],
        resource_file: str,
    ) -> str:
        chain_str = ".".join(access_chain)
        # Path params show as positional in the method call (matches the
        # Python emitter's signature).
        positional = ", ".join(snake(p.name) for p in m.path_params)
        # `**params` shorthand if the method takes a body OR query params.
        has_params = bool(m.body) or bool(m.query_params)
        params_file = (
            f"./src/{self.pkg}/types/"
            f"{snake(access_chain[-1])}_{snake(m.name)}_params.py"
        )
        params_link = (
            f'**<a href="{params_file}">params</a>' if has_params else ""
        )
        args = ", ".join(filter(None, [positional, params_link]))
        method_link = f'<a href="{resource_file}">{m.name}</a>'
        return f"client.{chain_str}.{method_link}({args})"

    def _return_link(self, m: Method, access_chain: tuple[str, ...]) -> str:
        # Look at the 200/2XX response (the typed one).
        for status in ("200", "201", "2XX", "default"):
            if status in m.responses:
                if m.pagination is not None:
                    page_cls = (
                        "SyncCursorPage"
                        if str(getattr(m.pagination.style, "value",
                                       m.pagination.style)) in ("cursor", "cursor_id")
                        else "SyncPage"
                    )
                    # Item type = the array element of the data field, with
                    # path-named-fallback for inline anonymous items.
                    item = self._page_item(m, access_chain)
                    return f"<a href=\"#\">{page_cls}[{item}]</a>"
                # Inline ObjectType has no global name — use the path-named
                # class the Python emitter creates (e.g. AgencyRetrieveResponse).
                from stainful.ir.types import ObjectType
                t = m.responses[status]
                if isinstance(t, ObjectType):
                    rendered = (
                        f"{pascal_singular_last(access_chain[-1])}"
                        f"{pascal(m.name)}Response"
                    )
                else:
                    rendered = self._render_type_name(t)
                response_file = (
                    f"./src/{self.pkg}/types/"
                    f"{snake(access_chain[-1])}_{snake(m.name)}_response.py"
                )
                return f'<a href="{response_file}">{rendered}</a>'
        return "None"

    # ----- helpers ----------------------------------------------------------
    def _render_type_name(self, t: Type) -> str:
        if isinstance(t, ModelRef):
            return pascal(t.name)
        if isinstance(t, PrimitiveType):
            return {
                PrimitiveKind.STRING: "str", PrimitiveKind.INTEGER: "int",
                PrimitiveKind.NUMBER: "float", PrimitiveKind.BOOLEAN: "bool",
                PrimitiveKind.BYTES: "bytes",
            }.get(t.kind, "object")
        if isinstance(t, ArrayType):
            return f"List[{self._render_type_name(t.item)}]"
        if isinstance(t, UnionType):
            return " | ".join(self._render_type_name(v) for v in t.variants)
        if isinstance(t, AnyType):
            return "object"
        return type(t).__name__

    def _page_item(self, m: Method, access_chain: tuple[str, ...]) -> str:
        # Paginated lists wrap items as `{data: List[Item], ...}`. The 200
        # response is usually a ModelRef → resolve it through `api.models`
        # to find the array item type. Fall back to `object` for opaque
        # shapes — better than guessing.
        for status in ("200", "201", "2XX"):
            t = m.responses.get(status)
            if t is None:
                continue
            obj = self._resolve_object(t)
            if obj is None:
                continue
            for p in obj.properties:
                if p.name == "data" and isinstance(p.type, ArrayType):
                    return self._render_type_name(p.type.item)
        return "object"

    def _resolve_object(self, t: Type):
        """Follow a single ModelRef hop to its ObjectType, else None."""
        from stainful.ir.types import ObjectType
        if isinstance(t, ObjectType):
            return t
        if isinstance(t, ModelRef):
            comp = self.api.models.get(t.name)
            if comp is not None and isinstance(comp.type, ObjectType):
                return comp.type
        return None

    def _resource_file_path(self, r: Resource, parent: tuple[str, ...]) -> str:
        name = snake(r.name)
        if r.subresources:
            return f"./src/{self.pkg}/resources/{'/'.join(parent + (name, name))}.py"
        return f"./src/{self.pkg}/resources/{'/'.join(parent + (name,))}.py"
