"""Python emitter (DESIGN §6 slice 5) — render the IR into an idiomatic SDK.

A *thin renderer* of an already-correct IR (DESIGN §2). The hand-written golden
target (`tests/golden/onebusaway/`) is the byte-shape this must reproduce; the
runtime is vendored verbatim into `<pkg>/_core/` (DESIGN §5 vendoring).

v1 simplification (noted, not hidden): all models are emitted into a single
`types/models.py` with `from __future__ import annotations`, so recursive /
forward refs resolve as strings without per-file cross-imports. Stainless uses
per-file; single-file is a deliberate v1 subtraction, additive to split later.
"""

from __future__ import annotations

import keyword
import re
import shutil
from pathlib import Path

from stainful.emit.python._casing import (
    brand,
    pascal,
    pascal_singular_last,
    package,
    singularize,
    snake,
)
from stainful.errors import StainfulError
from stainful.ir.model import (
    API,
    ContentType,
    HTTPVerb,
    Method,
    Resource,
    SecurityScheme,
)
from stainful.ir.types import (
    AnyType,
    ArrayType,
    EnumType,
    MapType,
    ModelRef,
    NullType,
    ObjectType,
    PrimitiveKind,
    PrimitiveType,
    Type,
    UnionType,
)

_RUNTIME = Path(__file__).parent.parent.parent / "runtime"

_PRIM = {
    PrimitiveKind.STRING: "str",
    PrimitiveKind.INTEGER: "int",
    PrimitiveKind.NUMBER: "float",
    PrimitiveKind.BOOLEAN: "bool",
    PrimitiveKind.BYTES: "bytes",
    PrimitiveKind.DATE: "date",
    PrimitiveKind.DATETIME: "datetime",
    PrimitiveKind.DECIMAL: "Decimal",
    PrimitiveKind.UUID: "str",
}

_HEADER = "# File generated by stainful — DO NOT EDIT.\n"

# Pydantic BaseModel reserves these attribute names — a field with one of
# these names collides at class-construction time (mypy: `Incompatible types
# in assignment, base class "BaseModel" defined the type as ...`). Mangle
# the Python field name with a trailing underscore and keep the wire name
# via `Field(alias="...")` — exactly the pattern Stainless uses (oracle:
# openai-python emits `schema_: Optional[Dict[str, object]] = FieldInfo(
# alias="schema", default=None)`). Same shape as the Python-keyword mangle.
_PYDANTIC_RESERVED = frozenset({
    "schema", "copy", "dict", "json", "parse_obj", "parse_raw",
    "parse_file", "validate", "construct", "fields", "from_orm",
    "model_dump", "model_dump_json", "model_validate", "model_config",
    "model_fields", "model_computed_fields", "model_extra",
    "model_fields_set", "model_post_init",
})

# Minimal subset of Stainless's top-level `_utils` that real consumer code and
# Stainless-generated test suites import. Not the full module — just the
# commonly-imported, well-defined helpers (drop-in surface).
_UTILS_SRC = '''from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any

__all__ = [
    "parse_date", "parse_datetime", "is_dict", "is_list", "is_mapping",
    "PropertyInfo",
]


class PropertyInfo:
    """Annotated-metadata marker (Stainless-compatible): carries the wire
    `alias` / `format` / `discriminator` for a request-params field. Used as
    `Annotated[T, PropertyInfo(alias="wireName")]` in *Params TypedDicts.
    """

    def __init__(self, *, alias=None, format=None, discriminator=None):
        self.alias = alias
        self.format = format
        self.discriminator = discriminator

    def __repr__(self):
        kw = ", ".join(
            f"{k}={v!r}" for k, v in vars(self).items() if v is not None
        )
        return f"PropertyInfo({kw})"


def parse_datetime(value: Any) -> datetime:
    if isinstance(value, datetime):
        return value
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=timezone.utc)
    s = value.decode() if isinstance(value, (bytes, bytearray)) else str(value)
    if s.endswith(("Z", "z")):
        s = s[:-1] + "+00:00"
    return datetime.fromisoformat(s)


def parse_date(value: Any) -> date:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=timezone.utc).date()
    s = value.decode() if isinstance(value, (bytes, bytearray)) else str(value)
    return date.fromisoformat(s[:10])


def is_dict(obj: object) -> bool:
    return isinstance(obj, dict)


def is_list(obj: object) -> bool:
    return isinstance(obj, list)


def is_mapping(obj: object) -> bool:
    from collections.abc import Mapping

    return isinstance(obj, Mapping)
'''


def _rcls(name: str) -> str:
    """Resource class name. Stainless convention is `<Pascal>Resource`
    (e.g. `AgencyResource`, `AsyncAgencyResource`), not bare `<Pascal>` —
    verified against the real Stainless-generated OneBusAway SDK. Matching it
    is part of the drop-in symbol contract.
    """
    return f"{pascal(name)}Resource"


class _Emitter:
    def __init__(self, api: API, out_dir: str) -> None:
        self.api = api
        self.pkg = package(api.name)
        self.brand = brand(api.name)
        self.out = Path(out_dir)
        self.root = self.out / self.pkg
        # component-schema-name -> shared class name (Stainless `$shared.models`
        # convention: e.g. component `Reference` -> class `References`). These
        # are emitted once and shared; everything else is component-local.
        self._shared: dict[str, str] = {
            comp: pascal(key) for comp, key in api.shared_models.items()
        }
        # Components that MUST stay standalone named classes (never inlined):
        # config $shared.models + discriminated-union variants (their tag field
        # must be a pydantic-visible Literal on a real class).
        self._named: set[str] = set(self._shared)
        # variant/owner class name -> {wire prop: tag literal}
        self._disc_overrides: dict[str, dict[str, str]] = {}
        for mdl in api.models.values():
            t = mdl.type
            if isinstance(t, UnionType) and t.discriminator and t.discriminator.mapping:
                for tagv, mname in t.discriminator.mapping.items():
                    self._named.add(mname)
                    self._disc_overrides.setdefault(
                        self._model_name(mname), {}
                    )[t.discriminator.property_name] = tagv
        # collected output, insertion-ordered: class name -> source
        self._classes: dict[str, str] = {}
        self._aliases: dict[str, str] = {}
        self._building: set[str] = set()
        # per-file types/ layout: which module each class/alias belongs to.
        # `_cur_module` is the render-context (single synchronous pass).
        self._cur_module: str = "shared"
        self._class_module: dict[str, str] = {}
        self._alias_module: dict[str, str] = {}

    def _model_name(self, component: str) -> str:
        """Emitted class name for a component schema (shared-aware)."""
        return self._shared.get(component, pascal(component))

    # --- model collector (Stainless per-operation path-named inlining) ----
    # Every operation owns a path-named model family
    # (`AgencyRetrieveResponse` -> `...ResponseData` -> `...ResponseDataEntry`).
    # Component schemas are INLINED under that path unless they are `$named`
    # (config $shared.models or discriminated-union variants) or on a $ref
    # cycle (auto-promoted to a standalone class). One eager recursive pass so
    # cycle state (`seen`) is never lost.

    def _render(self, t: Type, path: str, seen: frozenset[str]) -> str:
        if isinstance(t, PrimitiveType):
            return _PRIM.get(t.kind, "object")
        if isinstance(t, NullType):
            return "None"
        if isinstance(t, AnyType):
            return "object"
        if isinstance(t, EnumType):
            lits = ", ".join(repr(m.value) for m in t.members)
            return f"Literal[{lits}]" if lits else "str"
        if isinstance(t, ArrayType):
            return f"List[{self._render(t.item, path, seen)}]"
        if isinstance(t, MapType):
            return f"Dict[str, {self._render(t.value, path, seen)}]"
        if isinstance(t, UnionType):
            parts = [
                self._render(v, f"{path}Variant{i}", seen)
                for i, v in enumerate(t.variants)
            ]
            nn = sorted({x for x in parts if x != "None"})
            if "None" in parts:
                nn.append("None")
            if len(nn) == 1:
                return nn[0]
            union = f"Union[{', '.join(nn)}]"
            if t.discriminator is not None:
                return (
                    f'Annotated[{union}, '
                    f'Field(discriminator="{t.discriminator.property_name}")]'
                )
            return union
        if isinstance(t, ModelRef):
            name = t.name
            if name in self._named or name in self._shared:
                self._emit_named(name)
                return self._model_name(name)
            if name in seen:                       # $ref cycle -> promote
                self._named.add(name)
                self._emit_named(name)
                return self._model_name(name)
            comp = self.api.models.get(name)
            if comp is None:
                return "object"
            # Inside a SHARED model's subtree, Stainless keeps component refs
            # as named shared classes (golden References.agencies: List[Agency]).
            # Do NOT add to self._named — sharedness is CONTEXTUAL: the same
            # component is still path-inlined in op-response trees (golden has
            # both `Agency` shared AND `AgencyRetrieveResponseDataEntry`).
            if self._cur_module == "shared":
                self._emit_named(name)
                return self._model_name(name)
            return self._render(comp.type, path, seen | {name})  # inline
        if isinstance(t, ObjectType):
            return self._emit_object(pascal(path), t, seen)
        return "object"

    def _emit_object(
        self, cls: str, obj: ObjectType, seen: frozenset[str]
    ) -> str:
        if cls in self._classes or cls in self._building:
            return cls                              # done / breaking recursion
        self._building.add(cls)
        bases = [self._model_name(b.name) for b in obj.bases]
        for b in obj.bases:
            self._emit_named(b.name)
        lines = [f"class {cls}({', '.join(bases) or 'BaseModel'}):"]
        if not obj.properties:
            lines.append("    pass")
        for p in obj.properties:
            lines.append(self._field(p, cls, seen))
        self._building.discard(cls)
        self._classes[cls] = "\n".join(lines)
        self._class_module.setdefault(cls, self._cur_module)
        return cls

    def _emit_named(self, component: str) -> str:
        disp = self._model_name(component)
        if disp in self._classes or disp in self._aliases:
            return disp
        comp = self.api.models.get(component)
        if comp is None:
            return disp
        # $shared.models / promoted / disc-variant classes live in `shared`.
        prev, self._cur_module = self._cur_module, "shared"
        try:
            if isinstance(comp.type, ObjectType):
                return self._emit_object(disp, comp.type, frozenset({component}))
            self._aliases[disp] = (
                f"{disp} = {self._render(comp.type, disp, frozenset({component}))}"
            )
            self._alias_module[disp] = "shared"
            return disp
        finally:
            self._cur_module = prev

    @staticmethod
    def _py_field_name(pname: str) -> str:
        """Idiomatic field name, mangled only if it collides with a TRUE
        keyword (`from` -> `from_`, `2fa` -> `field_2fa`). Soft keywords
        (`type`, `match`, ...) are valid field names and must NOT be mangled —
        `type` only became soft in 3.12, so mangling it would diverge output
        across Python versions and break discriminated-union tag fields.
        """
        py = snake(pname)
        if not py or py[0].isdigit():
            py = f"field_{py}"
        if keyword.iskeyword(py) or py in _PYDANTIC_RESERVED:
            py = f"{py}_"
        return py

    def _field(self, p, owner_cls: str, seen: frozenset[str]) -> str:
        py = self._py_field_name(p.name)
        tag = self._disc_overrides.get(owner_cls, {}).get(p.name)
        if tag is not None:                         # discriminated-union tag
            lit = f"Literal[{tag!r}]"
            return (
                f'    {py}: {lit} = Field(alias="{p.name}")'
                if py != p.name else f"    {py}: {lit}"
            )
        # Stainless names an array-item model after the SINGULAR of the field.
        seg = pascal(p.name)
        if isinstance(p.type, ArrayType):
            seg = singularize(seg)
        ann = self._render(p.type, f"{owner_cls}{seg}", seen)
        if p.nullable:
            ann = f"Optional[{ann}]"
        needs_alias = py != p.name
        if p.required and not needs_alias:
            return f"    {py}: {ann}"
        if p.required and needs_alias:
            return f'    {py}: {ann} = Field(alias="{p.name}")'
        ann = ann if ann.startswith("Optional[") else f"Optional[{ann}]"
        if needs_alias:
            return f'    {py}: {ann} = Field(default=None, alias="{p.name}")'
        return f"    {py}: {ann} = None"

    _MODELS_PRELUDE = (
        "from __future__ import annotations\n\n"
        "from datetime import date, datetime  # noqa: F401\n"
        "from decimal import Decimal  # noqa: F401\n"
        "from typing import (  # noqa: F401\n"
        "    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,\n)\n\n"
        "from pydantic import Field  # noqa: F401\n\n"
        "from .._core._models import BaseModel  # noqa: F401\n"
        "from .._core._types import FileTypes  # noqa: F401\n"
        "from .._utils import PropertyInfo  # noqa: F401\n"
    )

    def _emit_models(self) -> None:
        # Per-file types/ layout (Stainless): one module per operation
        # (`agency_retrieve_response.py`) + `shared.py`. Classes/aliases were
        # registered while rendering resources; each carries its module.
        tdir = self.root / "types"
        tdir.mkdir(parents=True, exist_ok=True)

        # group: module -> ordered [(name, source, is_alias)]
        modules: dict[str, list[tuple[str, str, bool]]] = {}
        for name, src in self._classes.items():
            modules.setdefault(self._class_module.get(name, "shared"), []).append(
                (name, src, False)
            )
        for name, src in self._aliases.items():
            modules.setdefault(self._alias_module.get(name, "shared"), []).append(
                (name, src, True)
            )

        all_names = set(self._classes) | set(self._aliases)
        owner = {**self._class_module, **self._alias_module}
        for mod, items in modules.items():
            classes = [s for _n, s, a in items if not a]
            aliases = [s for _n, s, a in items if a]
            blob = "\n".join(classes + aliases)
            # import names that live in OTHER modules (shared bases, variants)
            cross: dict[str, list[str]] = {}
            for nm in sorted(all_names):
                o = owner.get(nm, "shared")
                if o != mod and re.search(rf"\b{re.escape(nm)}\b", blob):
                    cross.setdefault(o, []).append(nm)
            xi = "".join(
                f"from .{o} import {', '.join(sorted(ns))}\n"
                for o, ns in sorted(cross.items())
            )
            (tdir / f"{mod}.py").write_text(
                _HEADER + self._MODELS_PRELUDE + (xi and "\n" + xi) + "\n\n"
                + "\n\n\n".join(classes + aliases) + "\n"
            )

        exported = sorted(all_names)
        init = _HEADER + "from __future__ import annotations\n\n"
        for mod, items in sorted(modules.items()):
            names = sorted(n for n, _s, _a in items)
            init += f"from .{mod} import {', '.join(names)}\n"
        init += f"\n__all__ = {exported!r}\n"
        (tdir / "__init__.py").write_text(init)

    # --- methods / resources ---------------------------------------------
    def _return_type(self, m: Method, resource: str) -> str:
        for status in ("200", "201", "2XX", "default"):
            if status in m.responses:
                path = f"{pascal_singular_last(resource)}{pascal(m.name)}Response"
                self._cur_module = f"{snake(resource)}_{snake(m.name)}_response"
                return self._render(m.responses[status], path, frozenset())
        return "object"

    def _pagination(self, m: Method, resource: str, *, is_async: bool):
        """(PageClass, ItemAnnotation) for a paginated method, else None.

        Stainless returns `Sync/AsyncCursorPage[Item]` (RESEARCH §4 #1) — an
        object you iterate to transparently walk every page.
        """
        if not m.pagination:
            return None
        style = getattr(m.pagination.style, "value", m.pagination.style)
        kind = "CursorPage" if style in ("cursor", "cursor_id") else "Page"
        cls = f"{'Async' if is_async else 'Sync'}{kind}"
        # item type = element of the response's data array
        resp = m.responses.get("200") or next(iter(m.responses.values()), None)
        obj = self._resolve_object(resp) if resp is not None else None
        item = "object"
        data_key = (m.pagination.data_path or "data").split(".")[-1]
        if obj is not None:
            self._cur_module = f"{snake(resource)}_{snake(m.name)}_response"
            prefix = f"{pascal_singular_last(resource)}{pascal(m.name)}Response"
            for p in obj.properties:
                if p.name == data_key and isinstance(p.type, ArrayType):
                    item = self._render(
                        p.type.item, f"{prefix}{pascal(p.name)}", frozenset()
                    )
                    break
        return cls, item

    def _resolve_object(self, t: Type) -> ObjectType | None:
        if isinstance(t, ObjectType):
            return t
        if isinstance(t, ModelRef):
            mt = self.api.models.get(t.name)
            if mt is not None and isinstance(mt.type, ObjectType):
                return mt.type
        return None

    def _body_props(self, m: Method, resource: str):
        """[(py, wire, ann, required)] expanded from an object body (JSON,
        multipart, or form-urlencoded). Multipart binary fields are typed
        `FileTypes`. Falls back to a single opaque `body` param for
        non-object / streaming-binary bodies."""
        if m.body is None:
            return []
        ct = m.body.content_type
        root = f"{pascal_singular_last(resource)}{pascal(m.name)}Params"
        self._cur_module = f"{snake(resource)}_{snake(m.name)}_params"
        obj = (
            self._resolve_object(m.body.type)
            if ct in (ContentType.JSON, ContentType.MULTIPART, ContentType.FORM)
            else None
        )
        if obj is None:
            return [("body", None, self._render(m.body.type, root, frozenset()),
                     m.body.required)]
        out = []
        for p in obj.properties:
            if ct == ContentType.MULTIPART and isinstance(
                p.type, PrimitiveType
            ) and p.type.kind == PrimitiveKind.BYTES:
                ann = "FileTypes"          # binary upload field
            else:
                ann = self._render(p.type, f"{root}{pascal(p.name)}", frozenset())
            out.append((self._py_field_name(p.name), p.name, ann, p.required))
        return out

    def _emit_params_type(self, resource: str, m: Method, body_props, query_props):
        fields = list(body_props) + [(p[0], p[1], p[2], False) for p in query_props]
        if not fields:
            return
        name = f"{pascal_singular_last(resource)}{pascal(m.name)}Params"
        if name in self._classes:
            return
        lines = [f"class {name}(TypedDict, total=False):"]
        for py, wire, ann, *_ in fields:
            if wire and py != wire:
                lines.append(
                    f'    {py}: Annotated[{ann}, PropertyInfo(alias="{wire}")]'
                )
            else:
                lines.append(f"    {py}: {ann}")
        self._classes[name] = "\n".join(lines)
        self._class_module[name] = f"{snake(resource)}_{snake(m.name)}_params"

    def _webhook_unwrap_src(self, m: Method, resource: str) -> str:
        """Emit `unwrap()` + `verify_signature()` for a `type: webhook_unwrap`
        config method. The typed event is a discriminated union built from
        the config `event_types:` block (resolved into ModelRefs by the IR
        builder); absent → return type is `object`.
        """
        event_types = m.emit_hints.get("event_types") or {}
        disc = m.emit_hints.get("discriminator") or "type"

        if event_types:
            alias_name = f"{pascal_singular_last(resource)}{pascal(m.name)}Event"
            alias_module = f"{snake(resource)}_{snake(m.name)}_event"
            variants = sorted({
                self._emit_named(ref.name)
                for ref in event_types.values()
                if isinstance(ref, ModelRef)
            })
            if variants:
                # Annotated[Union[A, B, …], PropertyInfo(discriminator="type")]
                # — matches openai-python's `UnwrapWebhookEvent` shape.
                body = (
                    f"{alias_name} = Annotated[\n"
                    f"    Union[\n"
                    + "".join(f"        {v},\n" for v in variants)
                    + f"    ],\n"
                    f'    PropertyInfo(discriminator="{disc}"),\n'
                    f"]"
                )
                self._aliases[alias_name] = body
                self._alias_module[alias_name] = alias_module
                event_ann = alias_name
            else:
                event_ann = "object"
        else:
            event_ann = "object"

        doc = (m.docs or "").strip().replace('"""', "'''") or (
            "Verify the webhook signature (Standard Webhooks scheme) and "
            "parse the payload into the typed event."
        )
        unwrap = (
            f"    def {m.name}(\n"
            f"        self,\n"
            f"        payload: str | bytes,\n"
            f"        headers: Mapping[str, str],\n"
            f"        *,\n"
            f"        secret: str,\n"
            f"        tolerance: int = 300,\n"
            f"    ) -> {event_ann}:\n"
            f'        """{doc}"""\n'
            f"        return cast({event_ann}, _webhook_unwrap_event(\n"
            f"            payload, headers, secret=secret,\n"
            f"            event_type={event_ann}, tolerance=tolerance,\n"
            f"        ))"
        )
        verify = (
            "    def verify_signature(\n"
            "        self,\n"
            "        payload: str | bytes,\n"
            "        headers: Mapping[str, str],\n"
            "        *,\n"
            "        secret: str,\n"
            "        tolerance: int = 300,\n"
            "    ) -> None:\n"
            '        """Verify the Standard-Webhooks signature; raise '
            'InvalidWebhookSignatureError on failure."""\n'
            "        _webhook_verify_signature(\n"
            "            payload, headers, secret=secret, tolerance=tolerance,\n"
            "        )"
        )
        return unwrap + "\n\n" + verify

    def _method_src(self, m: Method, resource: str, *, is_async: bool) -> str:
        if m.emit_hints.get("type") == "webhook_unwrap":
            # Standard-Webhooks unwrap: verify HMAC-SHA256 signature, parse
            # JSON, validate into a typed event (discriminated union). No
            # HTTP call — `verb`/path-args/body machinery below would emit
            # garbage. openai-python's `client.webhooks.unwrap(...)` is the
            # oracle. Method body is sync in BOTH the sync and async resource
            # classes (the work is CPU-only — matches openai-python).
            return self._webhook_unwrap_src(m, resource)
        ret = self._return_type(m, resource)
        path_args = [snake(p.name) for p in m.path_params]
        path = m.path
        for p in m.path_params:
            path = path.replace("{" + p.name + "}", "{" + snake(p.name) + "}")
        verb = {
            HTTPVerb.GET: "_get", HTTPVerb.DELETE: "_delete",
            HTTPVerb.POST: "_post", HTTPVerb.PUT: "_put", HTTPVerb.PATCH: "_patch",
        }[m.http_verb]
        has_body_arg = verb in ("_post", "_put", "_patch")
        body_props = self._body_props(m, resource) if has_body_arg else []
        self._cur_module = f"{snake(resource)}_{snake(m.name)}_params"
        query_props = [
            (self._py_field_name(p.name), p.name,
             self._render(p.type,
                          f"{pascal_singular_last(resource)}{pascal(m.name)}Params{pascal(p.name)}",
                          frozenset()))
            for p in m.query_params
        ]
        # Stainless emits a `<Res><Method>Params` TypedDict for any operation
        # with non-path params. We keep our kwargs signature AND emit this as
        # an exported type (drop-in: `from pkg.types import XParams` works;
        # no signature change — advisor's concern avoided).
        self._emit_params_type(resource, m, body_props, query_props)

        st = m.streaming
        disc = st.discriminator if st else None
        if st:
            self._cur_module = f"{snake(resource)}_{snake(m.name)}_response"
        event_ann = (
            self._render(st.event_type,
                         f"{pascal_singular_last(resource)}{pascal(m.name)}Event", frozenset())
            if st else None
        )
        stream_cls = ("AsyncStream" if is_async else "Stream") if st else None

        pos = "".join(f"\n        {a}: str," for a in path_args)

        def kw_lines(stream_decl: str | None) -> str:
            req = [
                f"\n        {py}: {ann},"
                for py, _w, ann, r in body_props if r and py != disc
            ]
            if stream_decl:
                req.append(f"\n        {stream_decl}")
            opt = [
                f"\n        {py}: {ann} | NotGiven = not_given,"
                for py, _w, ann, r in body_props if not r and py != disc
            ]
            opt += [
                f"\n        {py}: {ann} | NotGiven = not_given,"
                for py, _w, ann in query_props
            ]
            tail = (
                "\n        extra_headers: Headers | None = None,"
                "\n        extra_query: Query | None = None,"
                "\n        extra_body: Body | None = None,"
                "\n        timeout: float | httpx.Timeout | None | NotGiven = not_given,"
            )
            return "".join(req) + "".join(opt) + tail

        guards = "\n".join(
            f'        if not {a}:\n'
            f'            raise ValueError(\n'
            f'                f"Expected a non-empty value for `{a}` '
            f'but received {{{a}!r}}"\n            )'
            for a in path_args
        )
        adef = "async def" if is_async else "def"
        await_ = "await " if is_async else ""
        doc = (m.docs or "").strip().replace('"""', "'''")

        # request body assembly (drops NOT_GIVEN; serializes models/dicts)
        all_body = [(py, w) for py, w, _a, _r in body_props]
        if disc and not any(py == disc for py, _ in all_body):
            all_body.append((disc, disc))
        body_build = ""
        body_kwarg = ""
        if has_body_arg and all_body:
            if m.body is not None and m.body.content_type == ContentType.BINARY:
                # raw octet-stream upload (S3 PUT object, GitHub release asset,
                # …). One opaque `body` param of `bytes` is sent verbatim;
                # never JSON-encoded, never dict-wrapped. The runtime sets
                # the `application/octet-stream` content-type.
                body_kwarg = "\n            body=body,\n            binary=True,"
            else:
                items = "".join(
                    f'\n            "{w}": {py},' for py, w in all_body
                )
                body_build = (
                    f"        _body = {{{items}\n        }}\n"
                    f"        _body = {{k: v for k, v in _body.items() "
                    f"if v is not not_given}}\n"
                )
                if m.body is not None and m.body.content_type == ContentType.MULTIPART:
                    # multipart: pass raw (files mustn't be JSON-coerced); the
                    # runtime splits file-like values into `files`, rest into `data`
                    body_kwarg = "\n            body=_body,\n            multipart=True,"
                else:
                    body_kwarg = "\n            body=to_jsonable(_body),"
        params_items = "".join(
            f'\n            "{w}": {py},' for py, w, _a in query_props
        )
        params_build = (
            f"        _params = {{{params_items}\n        }}\n"
            f"        _params = {{k: v for k, v in _params.items() "
            f"if v is not not_given}}\n"
            if query_props else ""
        )
        params_kwarg = "\n                params=_params," if query_props else ""

        def call(cast: str, extra: str) -> str:
            return (
                f"{await_}self.{verb}(\n"
                f'            f"{path}",{body_kwarg}\n'
                f"            options=make_request_options(\n"
                f"                extra_headers=extra_headers,\n"
                f"                extra_query=extra_query,\n"
                f"                extra_body=extra_body,\n"
                f"                timeout=timeout,{params_kwarg}\n"
                f"            ),\n"
                f"            cast_to={cast},{extra}\n"
                f"        )"
            )

        if st:
            # @overload pair + impl (RESEARCH §4 #6): stream=False -> model,
            # stream=True -> typed event Stream, identical sync/async surface.
            ov = "    @overload\n"
            o1 = (
                f"{ov}    {adef} {m.name}(\n        self,{pos}\n        *,"
                f"{kw_lines(f'{disc}: Literal[False] = False,')}\n"
                f"    ) -> {ret}: ...\n"
            )
            o2 = (
                f"{ov}    {adef} {m.name}(\n        self,{pos}\n        *,"
                f"{kw_lines(f'{disc}: Literal[True],')}\n"
                f"    ) -> {stream_cls}[{event_ann}]: ...\n"
            )
            extra = f"\n            stream={disc},\n            stream_cls={stream_cls},"
            impl = (
                f"    {adef} {m.name}(\n        self,{pos}\n        *,"
                f"{kw_lines(f'{disc}: bool = False,')}\n"
                f"    ) -> {ret} | {stream_cls}[{event_ann}]:\n"
                f'        """{doc}"""\n'
                f"{guards + chr(10) if guards else ''}"
                f"{body_build}{params_build}"
                f"        return {call(f'{event_ann} if {disc} else {ret}', extra)}"
            )
            return o1 + "\n" + o2 + "\n" + impl

        pag = self._pagination(m, resource, is_async=is_async)
        if pag:
            page_cls, item = pag
            ret_t = f"{page_cls}[{item}]"
            # Pagination config: wire param name + cursor response field,
            # both from stainless.yml. Emitted only when set so the runtime
            # falls through to defaults (`after`, `next_cursor`, last-item id).
            cfg_items: list[str] = []
            if m.pagination and m.pagination.cursor_param:
                cfg_items.append(
                    f'"cursor_param": "{m.pagination.cursor_param}"'
                )
            if m.pagination and m.pagination.cursor_response_field:
                cfg_items.append(
                    f'"cursor_response_field": '
                    f'"{m.pagination.cursor_response_field}"'
                )
            cfg_kwarg = (
                f"\n            pagination_cfg={{{', '.join(cfg_items)}}},"
                if cfg_items else ""
            )
            list_call = (
                f"{await_}self._get_api_list(\n"
                f'            f"{path}",\n'
                f"            page={ret_t},\n"
                f"            options=make_request_options(\n"
                f"                extra_headers=extra_headers,\n"
                f"                extra_query=extra_query,\n"
                f"                extra_body=extra_body,\n"
                f"                timeout=timeout,{params_kwarg}\n"
                f"            ),{cfg_kwarg}\n"
                f"        )"
            )
            return (
                f"    {adef} {m.name}(\n        self,{pos}\n        *,"
                f"{kw_lines(None)}\n    ) -> {ret_t}:\n"
                f'        """{doc}"""\n'
                f"{guards + chr(10) if guards else ''}"
                f"{params_build}"
                f"        return {list_call}"
            )

        return (
            f"    {adef} {m.name}(\n        self,{pos}\n        *,"
            f"{kw_lines(None)}\n    ) -> {ret}:\n"
            f'        """{doc}"""\n'
            f"{guards + chr(10) if guards else ''}"
            f"{body_build}{params_build}"
            f"        return {call(ret, '')}"
        )

    @staticmethod
    def _walk(resources: list[Resource]):
        """Yield every resource in the tree (top-level + nested)."""
        for r in resources:
            yield r
            yield from _Emitter._walk(r.subresources)

    def _sub_accessors(self, r: Resource, *, is_async: bool) -> str:
        pre = "Async" if is_async else ""
        return "\n\n".join(
            f"    @cached_property\n"
            f"    def {snake(s.name)}(self) -> {pre}{_rcls(s.name)}:\n"
            f"        return {pre}{_rcls(s.name)}(self._client)"
            for s in r.subresources
        )

    def _resource_src(self, r: Resource) -> str:
        cls = _rcls(r.name)
        sync_methods = "\n\n".join(
            [self._sub_accessors(r, is_async=False)] * bool(r.subresources)
            + [self._method_src(m, r.name, is_async=False) for m in r.methods]
        )
        async_methods = "\n\n".join(
            [self._sub_accessors(r, is_async=True)] * bool(r.subresources)
            + [self._method_src(m, r.name, is_async=True) for m in r.methods]
        )
        sub_import = "".join(
            f"from .{snake(s.name)} import Async{_rcls(s.name)}, {_rcls(s.name)}\n"
            for s in r.subresources
        )
        # Import exactly the model classes the generated source references —
        # membership against the known model universe (incl. synthetic),
        # word-boundary matched. Covers returns, params, body, event models.
        scan = sync_methods + "\n" + async_methods
        # every model class the collector has registered so far (this
        # resource's response/body rendering ran just above)
        known = set(self._classes) | set(self._aliases)
        used = sorted(n for n in known if re.search(rf"\b{re.escape(n)}\b", scan))
        models_import = (
            "from ..types import " + ", ".join(used) + "\n" if used else ""
        )
        # Resource-method signatures can carry inlined discriminated unions
        # (e.g. openai chat.completions.create takes `messages: List[Annotated[
        # Union[Variant0,...,Variant5], Field(discriminator="role")]]`) — so
        # they need the full typing/pydantic surface, not just the few names
        # that worked for OneBusAway.
        typing_needed = [
            t for t in (
                "Annotated", "Dict", "List", "Literal", "Mapping",
                "Optional", "Union", "cast", "overload",
            )
            if re.search(rf"\b{t}\b", scan)
        ]
        typing_import = (
            f"from typing import {', '.join(typing_needed)}\n"
            if typing_needed else ""
        )
        pydantic_import = (
            "from pydantic import Field\n"
            if re.search(r"\bField\s*\(", scan) else ""
        )
        webhook_import = (
            "from .._core._webhooks import (\n"
            "    unwrap_event as _webhook_unwrap_event,\n"
            "    verify_signature as _webhook_verify_signature,\n"
            ")\n"
            if "_webhook_unwrap_event(" in scan
            or "_webhook_verify_signature(" in scan
            else ""
        )
        stream_import = (
            "from .._core._streaming import AsyncStream, Stream\n"
            if re.search(r"\b(Async)?Stream\b", scan) else ""
        )
        jsonable_import = (
            "from .._core._models import to_jsonable\n"
            if "to_jsonable(" in scan else ""
        )
        pages = sorted({
            m.group(0)
            for m in re.finditer(r"\b(?:Sync|Async)(?:Cursor)?Page\b", scan)
        })
        pag_import = (
            f"from .._core.pagination import {', '.join(pages)}\n"
            if pages else ""
        )
        rn = snake(r.name)

        def wrapper(name: str, recv: str, fn: str) -> str:
            # Webhook methods are sync in BOTH classes (matches openai-python:
            # the work is CPU-only). The async raw/stream wrappers `await`
            # their function — wrapping a sync method would TypeError at
            # call time. openai-python itself doesn't expose
            # `with_raw_response.unwrap`, so skip wrapping webhook methods.
            wrapped_methods = [
                m for m in r.methods
                if m.emit_hints.get("type") != "webhook_unwrap"
            ]
            body = "\n".join(
                f"        self.{m.name} = {fn}({rn}.{m.name})"
                for m in wrapped_methods
            ) or "        pass"  # resources with only subresources have no methods
            return (
                f"class {name}:\n"
                f"    def __init__(self, {rn}: {recv}) -> None:\n{body}"
            )

        wrappers = "\n\n\n".join((
            wrapper(f"{cls}WithRawResponse", cls, "to_raw_response_wrapper"),
            wrapper(f"Async{cls}WithRawResponse", f"Async{cls}",
                    "async_to_raw_response_wrapper"),
            wrapper(f"{cls}WithStreamingResponse", cls,
                    "to_streamed_response_wrapper"),
            wrapper(f"Async{cls}WithStreamingResponse", f"Async{cls}",
                    "async_to_streamed_response_wrapper"),
        ))
        return f'''{_HEADER}from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
{typing_import}
import httpx

from .._core._request_options import make_request_options
from .._core._resource import AsyncAPIResource, SyncAPIResource
from .._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from .._core._sentinels import NotGiven, not_given
from .._core._types import Body, FileTypes, Headers, Query  # noqa: F401
{stream_import}{jsonable_import}{pag_import}{webhook_import}{pydantic_import}{sub_import}{models_import}
__all__ = ["{cls}", "Async{cls}"]


class {cls}(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> {cls}WithRawResponse:
        return {cls}WithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> {cls}WithStreamingResponse:
        return {cls}WithStreamingResponse(self)

{sync_methods}


class Async{cls}(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> Async{cls}WithRawResponse:
        return Async{cls}WithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> Async{cls}WithStreamingResponse:
        return Async{cls}WithStreamingResponse(self)

{async_methods}


{wrappers}
'''

    # --- client / package -------------------------------------------------
    def _auth_args(self, scheme: SecurityScheme | None) -> tuple[str, str, str]:
        """Return (env_name, key_param_name, super_auth_kwarg)."""
        if scheme is None:
            return "API_KEY", "key", "auth_query={}"
        env = scheme.read_env or f"{self.pkg.upper()}_API_KEY"
        if scheme.location == "query":
            return env, scheme.param_name or "key", (
                f'auth_query={{"{scheme.param_name or "key"}": api_key}}'
            )
        if scheme.kind.startswith("http"):
            return env, "Authorization", (
                'auth_headers={"Authorization": f"Bearer {api_key}"}'
            )
        return env, scheme.param_name or "X-API-Key", (
            f'auth_headers={{"{scheme.param_name or "X-API-Key"}": api_key}}'
        )

    def _client_src(self) -> str:
        resources = self.api.root.subresources
        env_url = next(iter(self.api.environments.values()), "")
        scheme = self.api.auth[0] if self.api.auth else None
        env, _, auth_kwarg = self._auth_args(scheme)
        # Reference resources via the package namespace — the brand client
        # class name can collide with a same-named top-level resource
        # (e.g. a "chat" API with a "chat" resource); `resources.Chat` is
        # unambiguous where bare `Chat` would resolve to the client class.
        imports = "from . import resources"

        def body(is_async: bool) -> str:
            pre = "Async" if is_async else ""
            base = "AsyncAPIClient" if is_async else "SyncAPIClient"
            hc = "httpx.AsyncClient" if is_async else "httpx.Client"
            attrs = "\n".join(
                f"    {snake(r.name)}: resources.{pre}{_rcls(r.name)}"
                for r in resources
            )
            inits = "\n".join(
                f"        self.{snake(r.name)} = resources.{pre}{_rcls(r.name)}(self)"
                for r in resources
            )
            return f'''class {pre}{self.brand}({base}):
{attrs}

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | httpx.URL | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int = 2,
        http_client: {hc} | None = None,
    ) -> None:
        if api_key is None:
            api_key = os.environ.get("{env}")
        if api_key is None:
            raise ValueError(
                "The api_key client option must be set either by passing api_key "
                "to the client or by setting the {env} environment variable"
            )
        super().__init__(
            base_url=base_url or os.environ.get("{self.pkg.upper()}_BASE_URL") or _DEFAULT_BASE_URL,
            timeout=timeout,
            max_retries=max_retries,
            http_client=http_client,
            {auth_kwarg},
        )
{inits}'''

        return f'''{_HEADER}from __future__ import annotations

import os

import httpx

from ._core._base_client import AsyncAPIClient, SyncAPIClient
from ._core._sentinels import NotGiven, not_given
{imports}

__all__ = ["{self.brand}", "Async{self.brand}"]

_DEFAULT_BASE_URL = "{env_url}"


{body(False)}


{body(True)}
'''

    def _pkg_init_src(self) -> str:
        errs = [
            "APIConnectionError", "APIError", "APIResponseValidationError",
            "APIStatusError", "APITimeoutError", "AuthenticationError",
            "BadRequestError", "ConflictError", "InternalServerError",
            "InvalidWebhookSignatureError", "NotFoundError",
            "PermissionDeniedError", "RateLimitError",
            "UnprocessableEntityError",
        ]
        return (
            _HEADER
            + f'"""{self.pkg} — generated by stainful (the open-source Stainless)."""\n\n'
            + "from __future__ import annotations\n\n"
            + f"from ._client import Async{self.brand}, {self.brand}\n"
            + "from ._core._exceptions import (\n"
            + "".join(f"    {e},\n" for e in errs)
            + ")\n"
            + "from ._core._sentinels import NOT_GIVEN, NotGiven, Omit, not_given, omit\n\n"
            # Stainless names the catch-all root `<Brand>Error` and roots the
            # hierarchy on it. APIError is our root; alias it so the Stainless
            # symbol `except <pkg>.<Brand>Error:` keeps working (drop-in).
            + f"{self.brand}Error = APIError\n\n"
            + f"__all__ = {['%s' % self.brand, 'Async%s' % self.brand, '%sError' % self.brand, 'NotGiven', 'not_given', 'NOT_GIVEN', 'Omit', 'omit', *errs]!r}\n"
        )

    def _generated_pyproject(self) -> str:
        return (
            f'[project]\nname = "{self.pkg}"\nversion = "{self.api.version}"\n'
            f'requires-python = ">=3.10"\n'
            f'dependencies = ["httpx>=0.27", "pydantic>=2.7"]\n\n'
            f"[build-system]\nrequires = [\"hatchling\"]\n"
            f'build-backend = "hatchling.build"\n'
        )

    # --- entry ------------------------------------------------------------
    def emit(self) -> None:
        if self.root.exists():
            shutil.rmtree(self.root)
        (self.root / "resources").mkdir(parents=True, exist_ok=True)

        # 1. vendor the runtime verbatim -> <pkg>/_core/ (DESIGN §5)
        core = self.root / "_core"
        shutil.copytree(_RUNTIME, core)
        (core / "__init__.py").write_text("")

        # 2a. $shared.models are a DECLARED public surface — emit them first
        #     (and their subtree) even if no operation references them, and so
        #     shared bases like ResponseWrapper precede their subclasses.
        for comp in self.api.shared_models:
            self._emit_named(comp)

        # 2b. one file per resource — the whole tree. Rendering each method's
        #     response/body registers its path-named model classes.
        all_resources = list(self._walk(self.api.root.subresources))
        resource_files = {
            snake(r.name): self._resource_src(r) for r in all_resources
        }
        self._emit_models()
        for fname, src in resource_files.items():
            (self.root / "resources" / f"{fname}.py").write_text(src)
        (self.root / "resources" / "__init__.py").write_text(
            _HEADER
            + "".join(
                f"from .{snake(r.name)} import "
                f"Async{_rcls(r.name)}, {_rcls(r.name)}\n"
                for r in all_resources
            )
        )

        # 3. client + package init + _utils (Stainless exposes a top-level
        #    `<pkg>._utils` with these date helpers; real consumer code and
        #    test suites import them — part of the drop-in surface) + pyproject
        (self.root / "_client.py").write_text(self._client_src())
        (self.root / "_utils.py").write_text(_HEADER + _UTILS_SRC)
        (self.root / "__init__.py").write_text(self._pkg_init_src())
        (self.out / "pyproject.toml").write_text(self._generated_pyproject())


def emit(api: API, out_dir: str) -> None:
    if not isinstance(api, API):
        raise StainfulError("emit expects an IR API instance")
    _Emitter(api, out_dir).emit()
