"""TypeScript emitter (Stage 2 of the v0.4 roadmap).

Same IR as the Python emitter — only the renderer differs. Generates a
TypeScript SDK whose symbol surface matches openai-node:

  - `<Brand>` client class extending `BaseClient` (instead of Python's
    `Sync<Brand>` / `Async<Brand>` split — TS has only one
    async-by-default flavor).
  - `<Name>Resource` per-resource class extending `APIResource`.
  - Methods return `Promise<T>` (deferred: `APIPromise<T>` with helpers).
  - Typed errors (`APIError` / `RateLimitError` / …) re-exported from
    the package root.
  - Per-resource files, types co-located. No `_<sdk>__init__.py`
    equivalent — `index.ts` is the root.

v0.1 scope (this slice):
  - ObjectType, PrimitiveType, ArrayType, ModelRef, UnionType, NullType,
    AnyType (the non-exotic types — OneBusAway-style schemas)
  - HTTP verbs: GET / POST / PUT / PATCH / DELETE
  - Path params + query params + JSON body / response

Deferred to follow-up slices: streaming, pagination, multipart,
discriminated unions, webhooks, MCP-from-TS.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from stainful.emit.python._casing import brand, pascal, snake
from stainful.errors import StainfulError
from stainful.ir.model import (
    API,
    ContentType,
    Method,
    Resource,
)
from stainful.ir.types import (
    AnyType,
    ArrayType,
    EnumType,
    MapType,
    ModelRef,
    NullType,
    ObjectType,
    PrimitiveKind,
    PrimitiveType,
    Type,
    UnionType,
)

_RUNTIME_TS = Path(__file__).parent.parent.parent / "runtime_ts"

# IR primitive → TS type.
_PRIM_TS = {
    PrimitiveKind.STRING: "string",
    PrimitiveKind.INTEGER: "number",
    PrimitiveKind.NUMBER: "number",
    PrimitiveKind.BOOLEAN: "boolean",
    PrimitiveKind.BYTES: "Blob",       # TS file/binary type
    PrimitiveKind.DATE: "string",       # ISO date; runtime keeps it as string
    PrimitiveKind.DATETIME: "string",
    PrimitiveKind.DECIMAL: "string",
    PrimitiveKind.UUID: "string",
}

_HEADER = "// File generated by stainful — DO NOT EDIT.\n"

# A bare TS identifier matches this; anything else needs to be a
# quoted string literal property name ("git.branch": string).
_TS_IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _ts_prop_name(wire: str) -> str:
    return wire if _TS_IDENT.match(wire) else f'"{wire}"'


def camel_method(name: str) -> str:
    """TS method-name convention: camelCase. Python keeps snake_case;
    real Stainless TS configs honor `casing.target.typescript` settings
    but the default is camelCase."""
    parts = name.replace("-", "_").split("_")
    parts = [p for p in parts if p]
    if not parts:
        return name
    return parts[0].lower() + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def emit_ts(api: API, out_dir: str) -> None:
    """Emit a TypeScript SDK at `out_dir`. Top-level layout:

        <pkg>/
          package.json
          tsconfig.json
          src/
            index.ts            (root exports)
            client.ts           (the brand class)
            _core/              (vendored runtime)
            resources/<name>.ts (one per resource leaf; nested dirs for
                                 subresources)
    """
    if not isinstance(api, API):
        raise StainfulError("emit_ts expects an IR API instance")
    _TSEmitter(api, out_dir).emit()


class _TSEmitter:
    def __init__(self, api: API, out_dir: str) -> None:
        self.api = api
        self.out = Path(out_dir)
        # TS package name: prefer the user-set Python package_name (works
        # as a sensible default for the TS package too — they often
        # match), fall back to brand-lower.
        self.pkg = api.python_package_name or _pkg_default(api.name)
        self.brand = brand(api.name)
        self.root = self.out / self.pkg
        # Track which named models have been emitted (avoid duplicates).
        self._emitted_models: set[str] = set()
        # Type definitions to write into the central types module.
        self._types_blocks: list[str] = []

    def emit(self) -> None:
        if self.root.exists():
            shutil.rmtree(self.root)
        (self.root / "src" / "resources").mkdir(parents=True, exist_ok=True)
        (self.root / "src" / "types").mkdir(parents=True, exist_ok=True)
        # 1. vendor the TS runtime as `src/_core/`
        core = self.root / "src" / "_core"
        shutil.copytree(_RUNTIME_TS, core)
        # 2. per-resource files (flat at v0.1 — nested layout is a polish item)
        resource_files: dict[str, str] = {}
        for r in self.api.root.subresources:
            self._collect_resource(r, resource_files)
        # 3. write types module (after all resources have rendered to gather refs)
        if self._types_blocks:
            (self.root / "src" / "types" / "index.ts").write_text(
                _HEADER + "\n".join(self._types_blocks) + "\n"
            )
        # 4. write resource files
        for fname, src in resource_files.items():
            (self.root / "src" / "resources" / fname).write_text(src)
        # 5. client.ts
        (self.root / "src" / "client.ts").write_text(self._client_src())
        # 6. index.ts (root exports)
        (self.root / "src" / "index.ts").write_text(self._index_src())
        # 7. package.json + tsconfig.json
        (self.root / "package.json").write_text(self._package_json())
        (self.root / "tsconfig.json").write_text(self._tsconfig())

    # ----- resource emission -----------------------------------------------
    def _collect_resource(
        self, r: Resource, files: dict[str, str], parent_chain: list[str] = (),  # type: ignore[assignment]
    ) -> None:
        files[f"{snake(r.name)}.ts"] = self._resource_src(r, parent_chain)
        for sub in r.subresources:
            self._collect_resource(sub, files, list(parent_chain) + [snake(r.name)])

    def _resource_src(self, r: Resource, parent_chain: list[str]) -> str:
        cls = f"{pascal(r.name)}Resource"
        # Param interfaces are TOP-LEVEL TS declarations (can't live
        # inside a class body); collect them per-method and emit them
        # before the class.
        method_blocks: list[tuple[str, str]] = []  # (interface_block, method_block)
        for m in r.methods:
            iface, meth = self._method_src(m, r.name)
            method_blocks.append((iface, meth))
        interfaces = "".join(b[0] for b in method_blocks)
        methods_src = "\n\n".join(b[1] for b in method_blocks)
        sub_decls = "\n".join(
            f"  {snake(s.name)}: {pascal(s.name)}Resource;"
            for s in r.subresources
        )
        sub_inits = "\n".join(
            f"    this.{snake(s.name)} = new {pascal(s.name)}Resource(client);"
            for s in r.subresources
        )
        sub_imports = "".join(
            f"import {{ {pascal(s.name)}Resource }} from './{snake(s.name)}';\n"
            for s in r.subresources
        )
        body = (
            (sub_decls + "\n" if sub_decls else "")
            + "  constructor(client: BaseClient) {\n"
            + "    super(client);\n"
            + (sub_inits + "\n" if sub_inits else "")
            + "  }\n\n"
            + methods_src
            + "\n"
        )
        # Scan the rendered source for known shared-model names; import
        # them precisely from `../types`. Mirrors the Python emitter.
        scan = interfaces + body
        used_types = sorted(
            n for n in self._emitted_models
            if re.search(rf"\b{re.escape(n)}\b", scan)
        )
        types_import = (
            f"import type {{ {', '.join(used_types)} }} from '../types';\n"
            if used_types else ""
        )
        # Import Stream when any of this resource's methods stream.
        stream_import = (
            "import { Stream } from '../_core/streaming';\n"
            if any(m.streaming is not None for m in r.methods) else ""
        )
        # Import CursorPage when any of this resource's methods paginate.
        pagination_import = (
            "import { CursorPage } from '../_core/pagination';\n"
            if any(m.pagination is not None for m in r.methods) else ""
        )
        return (
            _HEADER
            + "import { APIResource } from '../_core/resource';\n"
            + "import type { BaseClient, RequestOptions } from '../_core/client';\n"
            + stream_import
            + pagination_import
            + types_import
            + sub_imports
            + "\n"
            + interfaces
            + f"export class {cls} extends APIResource {{\n"
            + body
            + "}\n"
        )

    def _method_src(self, m: Method, resource_name: str) -> tuple[str, str]:
        """Returns `(top_level_interface_block, method_body)` so the
        resource emitter can hoist the param interface above the class.
        """
        path_args = [snake(p.name) for p in m.path_params]
        path_arg_decls = ", ".join(f"{a}: string" for a in path_args)
        param_fields: list[str] = []
        if m.body is not None and m.body.content_type == ContentType.JSON:
            obj = self._resolve_object(m.body.type)
            if obj is not None:
                for p in obj.properties:
                    ann = self._render_type(p.type)
                    optional = "" if p.required else "?"
                    if p.nullable:
                        ann = f"{ann} | null"
                    param_fields.append(f"  {_ts_prop_name(p.name)}{optional}: {ann};")
        for p in m.query_params:
            ann = self._render_type(p.type)
            optional = "" if p.required else "?"
            if p.nullable:
                ann = f"{ann} | null"
            param_fields.append(f"  {_ts_prop_name(p.name)}{optional}: {ann};")
        has_params = bool(param_fields)
        params_type_name = f"{pascal(resource_name)}{pascal(m.name)}Params"
        params_decl = f"params: {params_type_name}" if has_params else ""
        ret_type = self._method_return(m, resource_name)
        verb = m.http_verb.value.upper()
        path = m.path
        for p in m.path_params:
            path = path.replace("{" + p.name + "}", "${" + snake(p.name) + "}")
        body_arg = ""
        query_arg = ""
        if (
            m.body is not None
            and m.body.content_type == ContentType.JSON
            and has_params
        ):
            obj = self._resolve_object(m.body.type)
            body_keys = (
                [f'"{p.name}"' for p in obj.properties]
                if obj is not None else []
            )
            if body_keys:
                body_arg = (
                    "\n        body: Object.fromEntries(Object.entries(params)"
                    f".filter(([k]) => [{', '.join(body_keys)}].includes(k))),"
                )
        if m.query_params and has_params:
            qkeys = [f'"{p.name}"' for p in m.query_params]
            query_arg = (
                "\n        query: Object.fromEntries(Object.entries(params)"
                f".filter(([k]) => [{', '.join(qkeys)}].includes(k)))"
                f" as Record<string, string | number | boolean | undefined | null>,"
            )
        interface_block = (
            f"export interface {params_type_name} {{\n"
            + "\n".join(param_fields)
            + "\n}\n\n"
        ) if has_params else ""
        # Streaming methods (config `streaming:` block) get two overloads:
        # `stream: true` → `Promise<Stream<Event>>`; default → the JSON
        # response. The impl signature is the union.
        if m.streaming is not None:
            event_t = self._render_type(m.streaming.event_type)
            stream_union_ret = f"{ret_type} | Stream<{event_t}>"
            disc = m.streaming.discriminator or "stream"
            method_name = camel_method(m.name)
            # Build the two narrowing overloads. If has_params, we use
            # `Params & { stream?: false }` / `Params & { stream: true }`
            # so callers get perfect narrowing on the call site.
            if has_params:
                no_stream_args = ", ".join(filter(None, [
                    path_arg_decls,
                    f"params: {params_type_name} & {{ {disc}?: false }}",
                    "options?: Partial<RequestOptions>",
                ]))
                stream_args = ", ".join(filter(None, [
                    path_arg_decls,
                    f"params: {params_type_name} & {{ {disc}: true }}",
                    "options?: Partial<RequestOptions>",
                ]))
            else:
                no_stream_args = ", ".join(filter(None, [
                    path_arg_decls,
                    f"params: {{ {disc}?: false }}",
                    "options?: Partial<RequestOptions>",
                ]))
                stream_args = ", ".join(filter(None, [
                    path_arg_decls,
                    f"params: {{ {disc}: true }}",
                    "options?: Partial<RequestOptions>",
                ]))
            impl_args = ", ".join(filter(None, [
                path_arg_decls,
                params_decl or f"params: {{ {disc}?: boolean }}",
                "options?: Partial<RequestOptions>",
            ]))
            method_body = (
                f"  {method_name}({no_stream_args}): Promise<{ret_type}>;\n"
                f"  {method_name}({stream_args}): Promise<Stream<{event_t}>>;\n"
                f"  {method_name}({impl_args}): Promise<{stream_union_ret}> {{\n"
                f"    return this._client.request<{stream_union_ret}>({{\n"
                f"      method: '{verb}',\n"
                f"      path: `{path}`,"
                f"{query_arg}{body_arg}\n"
                f"      stream: !!(params as {{ {disc}?: boolean }})?.{disc},\n"
                f"      ...(options ?? {{}}),\n"
                f"    }});\n"
                f"  }}"
            )
        else:
            signature_args = ", ".join(filter(None, [
                path_arg_decls, params_decl, "options?: Partial<RequestOptions>",
            ]))
            pagination_arg = ""
            if m.pagination is not None:
                cfg_parts: list[str] = []
                if m.pagination.cursor_param:
                    cfg_parts.append(
                        f"cursorParam: '{m.pagination.cursor_param}'"
                    )
                else:
                    # Match the Python runtime's default — `after`.
                    cfg_parts.append("cursorParam: 'after'")
                if m.pagination.cursor_response_field:
                    cfg_parts.append(
                        f"cursorResponseField: "
                        f"'{m.pagination.cursor_response_field}'"
                    )
                pagination_arg = (
                    f"\n      pagination: {{ {', '.join(cfg_parts)} }},"
                )
            method_body = (
                f"  {camel_method(m.name)}({signature_args}): Promise<{ret_type}> {{\n"
                f"    return this._client.request<{ret_type}>({{\n"
                f"      method: '{verb}',\n"
                f"      path: `{path}`,"
                f"{query_arg}{body_arg}{pagination_arg}\n"
                f"      ...(options ?? {{}}),\n"
                f"    }});\n"
                f"  }}"
            )
        return interface_block, method_body

    def _method_return(self, m: Method, resource_name: str) -> str:
        # Paginated → `CursorPage<Item>`. The runtime wraps the parsed
        # response body when `RequestOptions.pagination` is set.
        if m.pagination is not None:
            item = self._page_item_type(m, resource_name)
            return f"CursorPage<{item}>"
        for status in ("200", "201", "2XX", "default"):
            if status in m.responses:
                t = m.responses[status]
                # Inline object → emit a named interface.
                if isinstance(t, ObjectType):
                    name = f"{pascal(resource_name)}{pascal(m.name)}Response"
                    self._emit_named_object(name, t)
                    return name
                return self._render_type(t)
        return "void"

    def _page_item_type(self, m: Method, resource_name: str) -> str:
        """Find the `data: List[T]` element type on the 200 response;
        render `T` as the page-item type. Fall back to `unknown` if the
        shape doesn't match."""
        for status in ("200", "201", "2XX"):
            if status not in m.responses:
                continue
            t = m.responses[status]
            obj = self._resolve_object(t) if isinstance(t, (ObjectType, ModelRef)) else None
            if obj is None:
                continue
            for p in obj.properties:
                if p.name == "data" and isinstance(p.type, ArrayType):
                    return self._render_type(p.type.item)
        return "unknown"

    # ----- type rendering --------------------------------------------------
    def _render_type(self, t: Type) -> str:
        if isinstance(t, PrimitiveType):
            return _PRIM_TS.get(t.kind, "unknown")
        if isinstance(t, NullType):
            return "null"
        if isinstance(t, AnyType):
            return "unknown"
        if isinstance(t, EnumType):
            return " | ".join(repr(m.value) for m in t.members) or "string"
        if isinstance(t, ArrayType):
            return f"Array<{self._render_type(t.item)}>"
        if isinstance(t, MapType):
            return f"Record<string, {self._render_type(t.value)}>"
        if isinstance(t, UnionType):
            return " | ".join(self._render_type(v) for v in t.variants) or "unknown"
        if isinstance(t, ModelRef):
            self._emit_model_ref(t.name)
            return pascal(t.name)
        if isinstance(t, ObjectType):
            # Inline → emit a structural type (a TS object literal type)
            fields = []
            for p in t.properties:
                ann = self._render_type(p.type)
                optional = "" if p.required else "?"
                if p.nullable:
                    ann = f"{ann} | null"
                fields.append(f"{_ts_prop_name(p.name)}{optional}: {ann}")
            return "{ " + "; ".join(fields) + " }"
        return "unknown"

    def _resolve_object(self, t: Type) -> ObjectType | None:
        if isinstance(t, ObjectType):
            return t
        if isinstance(t, ModelRef):
            comp = self.api.models.get(t.name)
            if comp is not None and isinstance(comp.type, ObjectType):
                return comp.type
        return None

    def _emit_named_object(self, name: str, obj: ObjectType) -> None:
        if name in self._emitted_models:
            return
        self._emitted_models.add(name)
        fields = []
        for p in obj.properties:
            ann = self._render_type(p.type)
            optional = "" if p.required else "?"
            if p.nullable:
                ann = f"{ann} | null"
            fields.append(f"  {_ts_prop_name(p.name)}{optional}: {ann};")
        self._types_blocks.append(
            f"export interface {name} {{\n" + "\n".join(fields) + "\n}\n"
        )

    def _emit_model_ref(self, component: str) -> None:
        name = pascal(component)
        if name in self._emitted_models:
            return
        comp = self.api.models.get(component)
        if comp is None:
            return
        if isinstance(comp.type, ObjectType):
            self._emit_named_object(name, comp.type)
        else:
            # Type alias (e.g. for a primitive-typed component schema)
            self._emitted_models.add(name)
            self._types_blocks.append(
                f"export type {name} = {self._render_type(comp.type)};\n"
            )

    # ----- top-level files -------------------------------------------------
    def _client_src(self) -> str:
        # Brand class extends BaseClient; sub-resource fields initialized
        # in the constructor (mirrors openai-node's client.ts).
        decls = "\n".join(
            f"  {snake(r.name)}: {pascal(r.name)}Resource;"
            for r in self.api.root.subresources
        )
        inits = "\n".join(
            f"    this.{snake(r.name)} = new {pascal(r.name)}Resource(this);"
            for r in self.api.root.subresources
        )
        imports = "".join(
            f"import {{ {pascal(r.name)}Resource }} from './resources/{snake(r.name)}';\n"
            for r in self.api.root.subresources
        )
        env = next(iter(self.api.environments.values()), "https://api.example.com")
        return (
            _HEADER
            + "import { BaseClient, type ClientOptions } from './_core/client';\n"
            + imports
            + "\n"
            + f"export class {self.brand} extends BaseClient {{\n"
            + (decls + "\n" if decls else "")
            + "  constructor(opts: ClientOptions = {}) {\n"
            + "    super(opts);\n"
            + (inits + "\n" if inits else "")
            + "  }\n\n"
            + "  protected override defaultBaseURL(): string {\n"
            + f"    return '{env}';\n"
            + "  }\n"
            + "}\n"
        )

    def _has_streaming(self) -> bool:
        """Any method in the resource tree configured for SSE streaming?"""
        def walk(rs: list[Resource]) -> bool:
            for r in rs:
                if any(m.streaming is not None for m in r.methods):
                    return True
                if walk(r.subresources):
                    return True
            return False
        return walk(self.api.root.subresources)

    def _has_pagination(self) -> bool:
        def walk(rs: list[Resource]) -> bool:
            for r in rs:
                if any(m.pagination is not None for m in r.methods):
                    return True
                if walk(r.subresources):
                    return True
            return False
        return walk(self.api.root.subresources)

    def _index_src(self) -> str:
        stream_export = (
            "export { Stream } from './_core/streaming';\n"
            if self._has_streaming() else ""
        )
        pagination_export = (
            "export { CursorPage } from './_core/pagination';\n"
            if self._has_pagination() else ""
        )
        return (
            _HEADER
            + f"export {{ {self.brand} }} from './client';\n"
            + f"export {{ {self.brand} as default }} from './client';\n"
            + "export type { ClientOptions } from './_core/client';\n"
            + stream_export
            + pagination_export
            + "export {\n"
            + "  APIConnectionError,\n"
            + "  APIError,\n"
            + "  APIResponseValidationError,\n"
            + "  APITimeoutError,\n"
            + "  APIUserAbortError,\n"
            + "  AuthenticationError,\n"
            + "  BadRequestError,\n"
            + "  ConflictError,\n"
            + "  InternalServerError,\n"
            + "  InvalidWebhookSignatureError,\n"
            + "  NotFoundError,\n"
            + "  PermissionDeniedError,\n"
            + "  RateLimitError,\n"
            + "  UnprocessableEntityError,\n"
            + "} from './_core/error';\n"
            + ("export * from './types';\n" if self._types_blocks else "")
        )

    def _package_json(self) -> str:
        return (
            "{\n"
            f'  "name": "{self.pkg}",\n'
            f'  "version": "{self.api.version}",\n'
            '  "type": "commonjs",\n'
            '  "main": "dist/index.js",\n'
            '  "types": "dist/index.d.ts",\n'
            '  "scripts": {\n'
            '    "build": "tsc -p tsconfig.json",\n'
            '    "check": "tsc -p tsconfig.json --noEmit"\n'
            '  }\n'
            "}\n"
        )

    def _tsconfig(self) -> str:
        return (
            "{\n"
            '  "compilerOptions": {\n'
            '    "target": "ES2022",\n'
            '    "module": "commonjs",\n'
            '    "lib": ["ES2022", "DOM"],\n'
            '    "strict": true,\n'
            '    "esModuleInterop": true,\n'
            '    "skipLibCheck": true,\n'
            '    "declaration": true,\n'
            '    "outDir": "dist",\n'
            '    "moduleResolution": "node"\n'
            "  },\n"
            '  "include": ["src/**/*.ts"]\n'
            "}\n"
        )


def _pkg_default(api_name: str) -> str:
    return api_name.replace("-sdk", "").replace("_", "-").lower()
