# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class AgencyRetrieveResponseDataEntry(BaseModel):
    disclaimer: Optional[str] = None
    email: Optional[str] = None
    fare_url: Optional[str] = Field(default=None, alias="fareUrl")
    id: str
    lang: Optional[str] = None
    name: str
    phone: Optional[str] = None
    private_service: Optional[bool] = Field(default=None, alias="privateService")
    timezone: str
    url: str


class AgencyRetrieveResponseData(BaseModel):
    entry: AgencyRetrieveResponseDataEntry
    references: References


class AgencyRetrieveResponse(ResponseWrapper):
    data: AgencyRetrieveResponseData
