# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class AgenciesWithCoverageListResponseDataList(BaseModel):
    agency_id: str = Field(alias="agencyId")
    lat: float
    lat_span: float = Field(alias="latSpan")
    lon: float
    lon_span: float = Field(alias="lonSpan")


class AgenciesWithCoverageListResponseData(BaseModel):
    limit_exceeded: Optional[bool] = Field(default=None, alias="limitExceeded")
    list: List[AgenciesWithCoverageListResponseDataList]
    references: References


class AgenciesWithCoverageListResponse(ResponseWrapper):
    data: AgenciesWithCoverageListResponseData
