# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class ArrivalAndDepartureRetrieveResponseDataEntryTripStatusLastKnownLocation(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class ArrivalAndDepartureRetrieveResponseDataEntryTripStatusPosition(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class ArrivalAndDepartureRetrieveResponseDataEntryTripStatus(BaseModel):
    active_trip_id: str = Field(alias="activeTripId")
    block_trip_sequence: int = Field(alias="blockTripSequence")
    closest_stop: str = Field(alias="closestStop")
    closest_stop_time_offset: Optional[int] = Field(default=None, alias="closestStopTimeOffset")
    distance_along_trip: float = Field(alias="distanceAlongTrip")
    frequency: Optional[str] = None
    last_known_distance_along_trip: float = Field(alias="lastKnownDistanceAlongTrip")
    last_known_location: Optional[ArrivalAndDepartureRetrieveResponseDataEntryTripStatusLastKnownLocation] = Field(default=None, alias="lastKnownLocation")
    last_known_orientation: Optional[float] = Field(default=None, alias="lastKnownOrientation")
    last_location_update_time: int = Field(alias="lastLocationUpdateTime")
    last_update_time: int = Field(alias="lastUpdateTime")
    next_stop: Optional[str] = Field(default=None, alias="nextStop")
    next_stop_time_offset: Optional[int] = Field(default=None, alias="nextStopTimeOffset")
    occupancy_capacity: int = Field(alias="occupancyCapacity")
    occupancy_count: int = Field(alias="occupancyCount")
    occupancy_status: str = Field(alias="occupancyStatus")
    orientation: Optional[float] = None
    phase: str
    position: Optional[ArrivalAndDepartureRetrieveResponseDataEntryTripStatusPosition] = None
    predicted: bool
    schedule_deviation: int = Field(alias="scheduleDeviation")
    scheduled_distance_along_trip: Optional[float] = Field(default=None, alias="scheduledDistanceAlongTrip")
    service_date: int = Field(alias="serviceDate")
    situation_ids: Optional[List[str]] = Field(default=None, alias="situationIds")
    status: str
    total_distance_along_trip: float = Field(alias="totalDistanceAlongTrip")
    vehicle_id: Optional[str] = Field(default=None, alias="vehicleId")


class ArrivalAndDepartureRetrieveResponseDataEntry(BaseModel):
    actual_track: Optional[str] = Field(default=None, alias="actualTrack")
    arrival_enabled: bool = Field(alias="arrivalEnabled")
    block_trip_sequence: int = Field(alias="blockTripSequence")
    departure_enabled: bool = Field(alias="departureEnabled")
    distance_from_stop: Optional[float] = Field(default=None, alias="distanceFromStop")
    frequency: Optional[str] = None
    historical_occupancy: Optional[str] = Field(default=None, alias="historicalOccupancy")
    last_update_time: Optional[int] = Field(default=None, alias="lastUpdateTime")
    number_of_stops_away: int = Field(alias="numberOfStopsAway")
    occupancy_status: Optional[str] = Field(default=None, alias="occupancyStatus")
    predicted: Optional[bool] = None
    predicted_arrival_interval: Optional[str] = Field(default=None, alias="predictedArrivalInterval")
    predicted_arrival_time: int = Field(alias="predictedArrivalTime")
    predicted_departure_interval: Optional[str] = Field(default=None, alias="predictedDepartureInterval")
    predicted_departure_time: int = Field(alias="predictedDepartureTime")
    predicted_occupancy: Optional[str] = Field(default=None, alias="predictedOccupancy")
    route_id: str = Field(alias="routeId")
    route_long_name: Optional[str] = Field(default=None, alias="routeLongName")
    route_short_name: Optional[str] = Field(default=None, alias="routeShortName")
    scheduled_arrival_interval: Optional[str] = Field(default=None, alias="scheduledArrivalInterval")
    scheduled_arrival_time: int = Field(alias="scheduledArrivalTime")
    scheduled_departure_interval: Optional[str] = Field(default=None, alias="scheduledDepartureInterval")
    scheduled_departure_time: int = Field(alias="scheduledDepartureTime")
    scheduled_track: Optional[str] = Field(default=None, alias="scheduledTrack")
    service_date: int = Field(alias="serviceDate")
    situation_ids: Optional[List[str]] = Field(default=None, alias="situationIds")
    status: Optional[str] = None
    stop_id: str = Field(alias="stopId")
    stop_sequence: int = Field(alias="stopSequence")
    total_stops_in_trip: int = Field(alias="totalStopsInTrip")
    trip_headsign: str = Field(alias="tripHeadsign")
    trip_id: str = Field(alias="tripId")
    trip_status: Optional[ArrivalAndDepartureRetrieveResponseDataEntryTripStatus] = Field(default=None, alias="tripStatus")
    vehicle_id: str = Field(alias="vehicleId")


class ArrivalAndDepartureRetrieveResponseData(BaseModel):
    entry: ArrivalAndDepartureRetrieveResponseDataEntry
    references: References


class ArrivalAndDepartureRetrieveResponse(ResponseWrapper):
    data: ArrivalAndDepartureRetrieveResponseData
