# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class BlockRetrieveResponseDataEntryConfigurationTripBlockStopTimeStopTime(BaseModel):
    stop_id: str = Field(alias="stopId")
    arrival_time: int = Field(alias="arrivalTime")
    departure_time: int = Field(alias="departureTime")
    pickup_type: Optional[int] = Field(default=None, alias="pickupType")
    drop_off_type: Optional[int] = Field(default=None, alias="dropOffType")


class BlockRetrieveResponseDataEntryConfigurationTripBlockStopTime(BaseModel):
    block_sequence: int = Field(alias="blockSequence")
    distance_along_block: float = Field(alias="distanceAlongBlock")
    accumulated_slack_time: float = Field(alias="accumulatedSlackTime")
    stop_time: BlockRetrieveResponseDataEntryConfigurationTripBlockStopTimeStopTime = Field(alias="stopTime")


class BlockRetrieveResponseDataEntryConfigurationTrip(BaseModel):
    trip_id: str = Field(alias="tripId")
    distance_along_block: float = Field(alias="distanceAlongBlock")
    accumulated_slack_time: float = Field(alias="accumulatedSlackTime")
    block_stop_times: List[BlockRetrieveResponseDataEntryConfigurationTripBlockStopTime] = Field(alias="blockStopTimes")


class BlockRetrieveResponseDataEntryConfiguration(BaseModel):
    active_service_ids: List[str] = Field(alias="activeServiceIds")
    inactive_service_ids: Optional[List[str]] = Field(default=None, alias="inactiveServiceIds")
    trips: List[BlockRetrieveResponseDataEntryConfigurationTrip]


class BlockRetrieveResponseDataEntry(BaseModel):
    id: str
    configurations: List[BlockRetrieveResponseDataEntryConfiguration]


class BlockRetrieveResponseData(BaseModel):
    entry: BlockRetrieveResponseDataEntry
    references: References


class BlockRetrieveResponse(ResponseWrapper):
    data: BlockRetrieveResponseData
