# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class ConfigRetrieveResponseDataEntryGitProperties(BaseModel):
    git_branch: Optional[str] = Field(default=None, alias="git.branch")
    git_build_host: Optional[str] = Field(default=None, alias="git.build.host")
    git_build_time: Optional[str] = Field(default=None, alias="git.build.time")
    git_build_user_email: Optional[str] = Field(default=None, alias="git.build.user.email")
    git_build_user_name: Optional[str] = Field(default=None, alias="git.build.user.name")
    git_build_version: Optional[str] = Field(default=None, alias="git.build.version")
    git_closest_tag_commit_count: Optional[str] = Field(default=None, alias="git.closest.tag.commit.count")
    git_closest_tag_name: Optional[str] = Field(default=None, alias="git.closest.tag.name")
    git_commit_id: Optional[str] = Field(default=None, alias="git.commit.id")
    git_commit_id_abbrev: Optional[str] = Field(default=None, alias="git.commit.id.abbrev")
    git_commit_id_describe: Optional[str] = Field(default=None, alias="git.commit.id.describe")
    git_commit_id_describe_short: Optional[str] = Field(default=None, alias="git.commit.id.describe-short")
    git_commit_message_full: Optional[str] = Field(default=None, alias="git.commit.message.full")
    git_commit_message_short: Optional[str] = Field(default=None, alias="git.commit.message.short")
    git_commit_time: Optional[str] = Field(default=None, alias="git.commit.time")
    git_commit_user_email: Optional[str] = Field(default=None, alias="git.commit.user.email")
    git_commit_user_name: Optional[str] = Field(default=None, alias="git.commit.user.name")
    git_dirty: Optional[str] = Field(default=None, alias="git.dirty")
    git_remote_origin_url: Optional[str] = Field(default=None, alias="git.remote.origin.url")
    git_tags: Optional[str] = Field(default=None, alias="git.tags")


class ConfigRetrieveResponseDataEntry(BaseModel):
    git_properties: Optional[ConfigRetrieveResponseDataEntryGitProperties] = Field(default=None, alias="gitProperties")
    id: Optional[str] = None
    name: Optional[str] = None
    service_date_from: Optional[str] = Field(default=None, alias="serviceDateFrom")
    service_date_to: Optional[str] = Field(default=None, alias="serviceDateTo")


class ConfigRetrieveResponseData(BaseModel):
    entry: ConfigRetrieveResponseDataEntry
    references: References


class ConfigRetrieveResponse(ResponseWrapper):
    data: ConfigRetrieveResponseData
