# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class ReportProblemWithStopRetrieveParams(TypedDict, total=False):
    code: Literal['stop_name_wrong', 'stop_number_wrong', 'stop_location_wrong', 'route_or_trip_missing', 'other']
    user_comment: Annotated[str, PropertyInfo(alias="userComment")]
    user_lat: Annotated[float, PropertyInfo(alias="userLat")]
    user_lon: Annotated[float, PropertyInfo(alias="userLon")]
    user_location_accuracy: Annotated[float, PropertyInfo(alias="userLocationAccuracy")]
