# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class ReportProblemWithTripRetrieveParams(TypedDict, total=False):
    service_date: Annotated[int, PropertyInfo(alias="serviceDate")]
    vehicle_id: Annotated[str, PropertyInfo(alias="vehicleID")]
    stop_id: Annotated[str, PropertyInfo(alias="stopID")]
    code: Literal['vehicle_never_came', 'vehicle_came_early', 'vehicle_came_late', 'wrong_headsign', 'vehicle_does_not_stop_here', 'other']
    user_comment: Annotated[str, PropertyInfo(alias="userComment")]
    user_on_vehicle: Annotated[bool, PropertyInfo(alias="userOnVehicle")]
    user_vehicle_number: Annotated[str, PropertyInfo(alias="userVehicleNumber")]
    user_lat: Annotated[float, PropertyInfo(alias="userLat")]
    user_lon: Annotated[float, PropertyInfo(alias="userLon")]
    user_location_accuracy: Annotated[float, PropertyInfo(alias="userLocationAccuracy")]
