# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class RoutesForLocationListResponseDataList(BaseModel):
    agency_id: str = Field(alias="agencyId")
    color: Optional[str] = None
    description: Optional[str] = None
    id: str
    long_name: Optional[str] = Field(default=None, alias="longName")
    null_safe_short_name: Optional[str] = Field(default=None, alias="nullSafeShortName")
    short_name: Optional[str] = Field(default=None, alias="shortName")
    text_color: Optional[str] = Field(default=None, alias="textColor")
    type: int
    url: Optional[str] = None


class RoutesForLocationListResponseData(BaseModel):
    limit_exceeded: Optional[bool] = Field(default=None, alias="limitExceeded")
    list: List[RoutesForLocationListResponseDataList]
    out_of_range: bool = Field(alias="outOfRange")
    references: References


class RoutesForLocationListResponse(ResponseWrapper):
    data: RoutesForLocationListResponseData
