# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class ScheduleForStopRetrieveResponseDataEntryStopRouteScheduleStopRouteDirectionScheduleScheduleFrequency(BaseModel):
    service_date: int = Field(alias="serviceDate")
    start_time: int = Field(alias="startTime")
    end_time: int = Field(alias="endTime")
    headway: int
    service_id: str = Field(alias="serviceId")
    trip_id: str = Field(alias="tripId")


class ScheduleForStopRetrieveResponseDataEntryStopRouteScheduleStopRouteDirectionScheduleScheduleStopTime(BaseModel):
    arrival_enabled: bool = Field(alias="arrivalEnabled")
    arrival_time: int = Field(alias="arrivalTime")
    departure_enabled: bool = Field(alias="departureEnabled")
    departure_time: int = Field(alias="departureTime")
    service_id: str = Field(alias="serviceId")
    stop_headsign: Optional[str] = Field(default=None, alias="stopHeadsign")
    trip_id: str = Field(alias="tripId")


class ScheduleForStopRetrieveResponseDataEntryStopRouteScheduleStopRouteDirectionSchedule(BaseModel):
    schedule_frequencies: Optional[List[ScheduleForStopRetrieveResponseDataEntryStopRouteScheduleStopRouteDirectionScheduleScheduleFrequency]] = Field(default=None, alias="scheduleFrequencies")
    schedule_stop_times: List[ScheduleForStopRetrieveResponseDataEntryStopRouteScheduleStopRouteDirectionScheduleScheduleStopTime] = Field(alias="scheduleStopTimes")
    trip_headsign: str = Field(alias="tripHeadsign")


class ScheduleForStopRetrieveResponseDataEntryStopRouteSchedule(BaseModel):
    route_id: str = Field(alias="routeId")
    stop_route_direction_schedules: List[ScheduleForStopRetrieveResponseDataEntryStopRouteScheduleStopRouteDirectionSchedule] = Field(alias="stopRouteDirectionSchedules")


class ScheduleForStopRetrieveResponseDataEntry(BaseModel):
    date: int
    stop_id: str = Field(alias="stopId")
    stop_route_schedules: List[ScheduleForStopRetrieveResponseDataEntryStopRouteSchedule] = Field(alias="stopRouteSchedules")


class ScheduleForStopRetrieveResponseData(BaseModel):
    entry: ScheduleForStopRetrieveResponseDataEntry
    references: References


class ScheduleForStopRetrieveResponse(ResponseWrapper):
    data: ScheduleForStopRetrieveResponseData
