# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import ResponseWrapper


class ScheduleForRouteRetrieveResponseDataEntryStopTripGroupingTripsWithStopTimeStopTime(BaseModel):
    arrival_enabled: bool = Field(alias="arrivalEnabled")
    arrival_time: int = Field(alias="arrivalTime")
    departure_enabled: bool = Field(alias="departureEnabled")
    departure_time: int = Field(alias="departureTime")
    service_id: Optional[str] = Field(default=None, alias="serviceId")
    stop_headsign: Optional[str] = Field(default=None, alias="stopHeadsign")
    stop_id: str = Field(alias="stopId")
    trip_id: str = Field(alias="tripId")


class ScheduleForRouteRetrieveResponseDataEntryStopTripGroupingTripsWithStopTime(BaseModel):
    trip_id: str = Field(alias="tripId")
    stop_times: List[ScheduleForRouteRetrieveResponseDataEntryStopTripGroupingTripsWithStopTimeStopTime] = Field(alias="stopTimes")


class ScheduleForRouteRetrieveResponseDataEntryStopTripGrouping(BaseModel):
    direction_id: str = Field(alias="directionId")
    stop_ids: List[str] = Field(alias="stopIds")
    trip_headsigns: List[str] = Field(alias="tripHeadsigns")
    trip_ids: List[str] = Field(alias="tripIds")
    trips_with_stop_times: Optional[List[ScheduleForRouteRetrieveResponseDataEntryStopTripGroupingTripsWithStopTime]] = Field(default=None, alias="tripsWithStopTimes")


class ScheduleForRouteRetrieveResponseDataEntry(BaseModel):
    route_id: str = Field(alias="routeId")
    schedule_date: int = Field(alias="scheduleDate")
    service_ids: List[str] = Field(alias="serviceIds")
    stop_trip_groupings: List[ScheduleForRouteRetrieveResponseDataEntryStopTripGrouping] = Field(alias="stopTripGroupings")


class ScheduleForRouteRetrieveResponseData(BaseModel):
    entry: ScheduleForRouteRetrieveResponseDataEntry


class ScheduleForRouteRetrieveResponse(ResponseWrapper):
    data: ScheduleForRouteRetrieveResponseData
