# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class Agency(BaseModel):
    disclaimer: Optional[str] = None
    email: Optional[str] = None
    fare_url: Optional[str] = Field(default=None, alias="fareUrl")
    id: str
    lang: Optional[str] = None
    name: str
    phone: Optional[str] = None
    private_service: Optional[bool] = Field(default=None, alias="privateService")
    timezone: str
    url: str


class Route(BaseModel):
    agency_id: str = Field(alias="agencyId")
    color: Optional[str] = None
    description: Optional[str] = None
    id: str
    long_name: Optional[str] = Field(default=None, alias="longName")
    null_safe_short_name: Optional[str] = Field(default=None, alias="nullSafeShortName")
    short_name: Optional[str] = Field(default=None, alias="shortName")
    text_color: Optional[str] = Field(default=None, alias="textColor")
    type: int
    url: Optional[str] = None


class SituationSummary(BaseModel):
    lang: Optional[str] = None
    value: Optional[str] = None


class SituationDescription(BaseModel):
    lang: Optional[str] = None
    value: Optional[str] = None


class SituationURL(BaseModel):
    lang: Optional[str] = None
    value: Optional[str] = None


class SituationActiveWindow(BaseModel):
    from_: Optional[int] = Field(default=None, alias="from")
    to: Optional[int] = None


class SituationAllAffect(BaseModel):
    agency_id: Optional[str] = Field(default=None, alias="agencyId")
    application_id: Optional[str] = Field(default=None, alias="applicationId")
    direction_id: Optional[str] = Field(default=None, alias="directionId")
    route_id: Optional[str] = Field(default=None, alias="routeId")
    stop_id: Optional[str] = Field(default=None, alias="stopId")
    trip_id: Optional[str] = Field(default=None, alias="tripId")


class SituationConsequenceConditionDetailsDiversionPath(BaseModel):
    length: Optional[int] = None
    levels: Optional[str] = None
    points: Optional[str] = None


class SituationConsequenceConditionDetails(BaseModel):
    diversion_path: Optional[SituationConsequenceConditionDetailsDiversionPath] = Field(default=None, alias="diversionPath")
    diversion_stop_ids: Optional[List[str]] = Field(default=None, alias="diversionStopIds")


class SituationConsequence(BaseModel):
    condition: Optional[str] = None
    condition_details: Optional[SituationConsequenceConditionDetails] = Field(default=None, alias="conditionDetails")


class TimeWindow(BaseModel):
    from_: int = Field(alias="from")
    to: int


class Situation(BaseModel):
    id: str
    creation_time: int = Field(alias="creationTime")
    reason: Optional[str] = None
    summary: Optional[SituationSummary] = None
    description: Optional[SituationDescription] = None
    url: Optional[SituationURL] = None
    active_windows: Optional[List[SituationActiveWindow]] = Field(default=None, alias="activeWindows")
    all_affects: Optional[List[SituationAllAffect]] = Field(default=None, alias="allAffects")
    consequences: Optional[List[SituationConsequence]] = None
    publication_windows: Optional[List[TimeWindow]] = Field(default=None, alias="publicationWindows")
    severity: Optional[str] = None
    consequence_message: Optional[str] = Field(default=None, alias="consequenceMessage")


class StopTime(BaseModel):
    arrival_time: Optional[int] = Field(default=None, alias="arrivalTime")
    departure_time: Optional[int] = Field(default=None, alias="departureTime")
    distance_along_trip: Optional[float] = Field(default=None, alias="distanceAlongTrip")
    historical_occupancy: Optional[str] = Field(default=None, alias="historicalOccupancy")
    stop_headsign: Optional[str] = Field(default=None, alias="stopHeadsign")
    stop_id: Optional[str] = Field(default=None, alias="stopId")


class Stop(BaseModel):
    code: Optional[str] = None
    direction: Optional[str] = None
    id: str
    lat: float
    location_type: int = Field(alias="locationType")
    lon: float
    name: str
    parent: str
    route_ids: List[str] = Field(alias="routeIds")
    static_route_ids: List[str] = Field(alias="staticRouteIds")
    wheelchair_boarding: Optional[str] = Field(default=None, alias="wheelchairBoarding")


class Trip(BaseModel):
    block_id: Optional[str] = Field(default=None, alias="blockId")
    direction_id: Optional[str] = Field(default=None, alias="directionId")
    id: str
    peak_offpeak: Optional[int] = Field(default=None, alias="peakOffpeak")
    route_id: str = Field(alias="routeId")
    route_short_name: Optional[str] = Field(default=None, alias="routeShortName")
    service_id: str = Field(alias="serviceId")
    shape_id: Optional[str] = Field(default=None, alias="shapeId")
    time_zone: Optional[str] = Field(default=None, alias="timeZone")
    trip_headsign: Optional[str] = Field(default=None, alias="tripHeadsign")
    trip_short_name: Optional[str] = Field(default=None, alias="tripShortName")


class References(BaseModel):
    agencies: List[Agency]
    routes: List[Route]
    situations: List[Situation]
    stop_times: List[StopTime] = Field(alias="stopTimes")
    stops: List[Stop]
    trips: List[Trip]


class ResponseWrapper(BaseModel):
    code: int
    current_time: int = Field(alias="currentTime")
    text: str
    version: int
