# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class StopRetrieveResponseDataEntry(BaseModel):
    code: Optional[str] = None
    direction: Optional[str] = None
    id: str
    lat: float
    location_type: int = Field(alias="locationType")
    lon: float
    name: str
    parent: str
    route_ids: List[str] = Field(alias="routeIds")
    static_route_ids: List[str] = Field(alias="staticRouteIds")
    wheelchair_boarding: Optional[str] = Field(default=None, alias="wheelchairBoarding")


class StopRetrieveResponseData(BaseModel):
    entry: StopRetrieveResponseDataEntry
    references: References


class StopRetrieveResponse(ResponseWrapper):
    data: StopRetrieveResponseData
