# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class StopsForRouteListResponseDataEntryPolyline(BaseModel):
    length: Optional[int] = None
    levels: Optional[str] = None
    points: Optional[str] = None


class StopsForRouteListResponseDataEntryStopGroupingName(BaseModel):
    name: Optional[str] = None
    names: Optional[List[str]] = None
    type: Optional[str] = None


class StopsForRouteListResponseDataEntryStopGroupingPolyline(BaseModel):
    length: Optional[int] = None
    levels: Optional[str] = None
    points: Optional[str] = None


class StopsForRouteListResponseDataEntryStopGrouping(BaseModel):
    id: Optional[str] = None
    name: Optional[StopsForRouteListResponseDataEntryStopGroupingName] = None
    polylines: Optional[List[StopsForRouteListResponseDataEntryStopGroupingPolyline]] = None
    stop_ids: Optional[List[str]] = Field(default=None, alias="stopIds")


class StopsForRouteListResponseDataEntry(BaseModel):
    polylines: Optional[List[StopsForRouteListResponseDataEntryPolyline]] = None
    route_id: Optional[str] = Field(default=None, alias="routeId")
    stop_groupings: Optional[List[StopsForRouteListResponseDataEntryStopGrouping]] = Field(default=None, alias="stopGroupings")
    stop_ids: Optional[List[str]] = Field(default=None, alias="stopIds")


class StopsForRouteListResponseData(BaseModel):
    entry: StopsForRouteListResponseDataEntry
    references: References


class StopsForRouteListResponse(ResponseWrapper):
    data: StopsForRouteListResponseData
