# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class TripDetailRetrieveParams(TypedDict, total=False):
    service_date: Annotated[int, PropertyInfo(alias="serviceDate")]
    include_trip: Annotated[bool, PropertyInfo(alias="includeTrip")]
    include_schedule: Annotated[bool, PropertyInfo(alias="includeSchedule")]
    include_status: Annotated[bool, PropertyInfo(alias="includeStatus")]
    time: int
