# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class TripRetrieveResponseDataEntry(BaseModel):
    block_id: Optional[str] = Field(default=None, alias="blockId")
    direction_id: Optional[str] = Field(default=None, alias="directionId")
    id: str
    peak_offpeak: Optional[int] = Field(default=None, alias="peakOffpeak")
    route_id: str = Field(alias="routeId")
    route_short_name: Optional[str] = Field(default=None, alias="routeShortName")
    service_id: str = Field(alias="serviceId")
    shape_id: Optional[str] = Field(default=None, alias="shapeId")
    time_zone: Optional[str] = Field(default=None, alias="timeZone")
    trip_headsign: Optional[str] = Field(default=None, alias="tripHeadsign")
    trip_short_name: Optional[str] = Field(default=None, alias="tripShortName")


class TripRetrieveResponseData(BaseModel):
    entry: TripRetrieveResponseDataEntry
    references: References


class TripRetrieveResponse(ResponseWrapper):
    data: TripRetrieveResponseData
