# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401

from .shared import References, ResponseWrapper


class VehiclesForAgencyListResponseDataListLocation(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class VehiclesForAgencyListResponseDataListTripStatusLastKnownLocation(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class VehiclesForAgencyListResponseDataListTripStatusPosition(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class VehiclesForAgencyListResponseDataListTripStatus(BaseModel):
    active_trip_id: str = Field(alias="activeTripId")
    block_trip_sequence: int = Field(alias="blockTripSequence")
    closest_stop: str = Field(alias="closestStop")
    closest_stop_time_offset: Optional[int] = Field(default=None, alias="closestStopTimeOffset")
    distance_along_trip: float = Field(alias="distanceAlongTrip")
    frequency: Optional[str] = None
    last_known_distance_along_trip: float = Field(alias="lastKnownDistanceAlongTrip")
    last_known_location: Optional[VehiclesForAgencyListResponseDataListTripStatusLastKnownLocation] = Field(default=None, alias="lastKnownLocation")
    last_known_orientation: Optional[float] = Field(default=None, alias="lastKnownOrientation")
    last_location_update_time: int = Field(alias="lastLocationUpdateTime")
    last_update_time: int = Field(alias="lastUpdateTime")
    next_stop: Optional[str] = Field(default=None, alias="nextStop")
    next_stop_time_offset: Optional[int] = Field(default=None, alias="nextStopTimeOffset")
    occupancy_capacity: int = Field(alias="occupancyCapacity")
    occupancy_count: int = Field(alias="occupancyCount")
    occupancy_status: str = Field(alias="occupancyStatus")
    orientation: Optional[float] = None
    phase: str
    position: Optional[VehiclesForAgencyListResponseDataListTripStatusPosition] = None
    predicted: bool
    schedule_deviation: int = Field(alias="scheduleDeviation")
    scheduled_distance_along_trip: Optional[float] = Field(default=None, alias="scheduledDistanceAlongTrip")
    service_date: int = Field(alias="serviceDate")
    situation_ids: Optional[List[str]] = Field(default=None, alias="situationIds")
    status: str
    total_distance_along_trip: float = Field(alias="totalDistanceAlongTrip")
    vehicle_id: Optional[str] = Field(default=None, alias="vehicleId")


class VehiclesForAgencyListResponseDataList(BaseModel):
    vehicle_id: str = Field(alias="vehicleId")
    last_update_time: int = Field(alias="lastUpdateTime")
    last_location_update_time: int = Field(alias="lastLocationUpdateTime")
    location: Optional[VehiclesForAgencyListResponseDataListLocation] = None
    trip_id: Optional[str] = Field(default=None, alias="tripId")
    trip_status: Optional[VehiclesForAgencyListResponseDataListTripStatus] = Field(default=None, alias="tripStatus")
    occupancy_capacity: Optional[int] = Field(default=None, alias="occupancyCapacity")
    occupancy_count: Optional[int] = Field(default=None, alias="occupancyCount")
    occupancy_status: Optional[str] = Field(default=None, alias="occupancyStatus")
    phase: Optional[str] = None
    status: Optional[str] = None


class VehiclesForAgencyListResponseData(BaseModel):
    list: List[VehiclesForAgencyListResponseDataList]
    limit_exceeded: Optional[bool] = Field(default=None, alias="limitExceeded")
    references: References


class VehiclesForAgencyListResponse(ResponseWrapper):
    data: VehiclesForAgencyListResponseData
